export const eventConfig = {
  brideName: "Vanessa",
  groomName: "Eliran",
  brideNameHe: "ונסה",
  groomNameHe: "אלירן",
  initials: "E&V",
  quote: "כִּי אָמַרְתִּי עוֹלָם חֶסֶד יִבָּנֶה",
  date: new Date("2026-06-24T19:00:00+03:00"),
  dateShort: "24 / 6",
  dateLabel: "יום רביעי, ט׳ בתמוז תשפ״ו",
  timeLabel: "קבלת פנים: 19:00 · חופה: 20:30",
  venue: "קו המים",
  venueTagline: "Events by the Sea",
  venueSubtitle: "קו המים · נתניה",
  address: "חוף הצוק הצפוני, נתניה",
  wazeUrl: "https://waze.com/ul?q=קו המים נתניה",
  venueUrl: "https://kavhamaim.co.il/",
  heroImage: "/save-the-date.svg",
  groomParents: {
    label: "הורי החתן",
    names: ["משה חמו", "איריס מורנו"],
  },
  brideParents: {
    label: "הורי הכלה",
    names: ["אליאן אבוחצירא", "יעקב אבוחצירא"],
  },
};
