export const eventConfig = {
  brideName: "Vanessa",
  groomName: "Eliran",
  brideNameHe: "ונסה",
  groomNameHe: "אלירן",
  initials: "E&V",
  quote: "וְאֵרַשְׂתִּיךְ לִי לְעוֹלָם",
  date: new Date("2026-06-24T19:00:00+03:00"),
  dateShort: "24 / 6",
  dateLabel: "יום רביעי, ח׳ בתמוז תשפ״ו",
  timeLabel: "קבלת פנים: 19:00 · חופה: 20:30",
  venue: "אחוזת החוף",
  address: "רח׳ החוף 1, הרצליה",
  wazeUrl: "https://waze.com/ul?q=אחוזת החוף הרצליה",
  heroImage: "/save-the-date.svg",
};
