import type { Place } from "./types";

/**
 * הקואורדינטות נבדקו מול מפות פתוחות, אבל מקומות בתאילנד זזים —
 * כל מקום שמסומן approx צריך אימות בגוגל מפות לפני שנוסעים אליו.
 * מסעדות ובתי חב"ד: תמיד להתקשר/לבדוק שעות לפני, במיוחד בחגים.
 */
export const PLACES: Place[] = [
  // ─────────────────────────── בנגקוק ───────────────────────────
  {
    id: "chabad-bangkok-khaosan",
    name: 'בית חב"ד בנגקוק — קאו סאן',
    nameEn: "Chabad House Bangkok (Khaosan)",
    region: "bangkok",
    category: "chabad",
    lat: 13.762,
    lng: 100.4975,
    approx: true,
    address: "Phra Sumen Rd, Talat Yot, Phra Nakhon, Bangkok",
    hook: "המרכז הישראלי של בנגקוק — פרה סומן רואד, דקות מקאו סאן ומרמבוטרי.",
    details:
      'בית הכנסת, מסעדת "בית אלישבע" הכשרה, ארוחות שבת וחג, ומידע לישראלים. בסוכות יש סוכה גדולה בחצר.',
    tip: 'להירשם לסעודות שבת/חג מראש דרך האתר או בטלפון — בסוכות זה מתמלא. תרומה מקובלת ~300-500 באט לסעודה.',
    url: "https://www.chabadthailand.com/",
  },
  {
    id: "chabad-bangkok-sukhumvit",
    name: "מסעדות כשרות בסוכומוויט",
    nameEn: "Kosher restaurants, Sukhumvit",
    region: "bangkok",
    category: "kosher",
    lat: 13.735,
    lng: 100.56,
    approx: true,
    address: "Mille Malle Mall, קומה 3, Sukhumvit Soi 20, Khlong Toei",
    hours: 'חלבית: א\'-ה\' 9:00-20:30 · שישי 9:00-15:00 · מוצ"ש עד 22:00',
    hook: "שתי מסעדות כשרות למהדרין באותה קומה — בשרית ביחידה 303, חלבית ב-302.",
    details:
      "הבשרית: שווארמה, שניצל, שיפודים וצ'יפס. הצד המודרני של העיר, ליד BTS אסוק.",
    tip: "רלוונטי אם אתם ישנים בסוכומוויט. אם אתם בקאו סאן — חב\"ד קאו סאן קרוב יותר.",
    priceThb: 450,
  },
  {
    id: "kosher-bet-elisheva",
    name: 'המסעדה הבשרית — חב"ד קאו סאן',
    nameEn: "Meat Restaurant, Chabad Bangkok",
    region: "bangkok",
    category: "kosher",
    lat: 13.762,
    lng: 100.4975,
    approx: true,
    address: "Phra Sumen Rd, Talat Yot, Phra Nakhon, Bangkok",
    hours: 'א\'-ה\' 13:00-22:00 · שישי 10:00-15:00 · מוצ"ש עד 22:00',
    hook: 'המסעדה הכשרה של חב"ד קאו סאן — בשרי, ישראלי, מנות גדולות.',
    details:
      "באותו בניין יש גם מסעדה חלבית בהשגחת מהדרין, ויש גם משלוחים.",
    tip: "אחרי טיסה ארוכה זה המקום הראשון שכדאי לכם, וגם המקום להזמין ממנו אוכל לדרך.",
    priceThb: 400,
  },
  {
    id: "dairy-bangkok",
    name: 'המסעדה החלבית — חב"ד קאו סאן',
    nameEn: "Dairy Restaurant, Chabad Bangkok",
    region: "bangkok",
    category: "kosher",
    lat: 13.7622,
    lng: 100.4978,
    approx: true,
    address: "Phra Sumen Rd, Talat Yot, Phra Nakhon",
    hook: 'חלבית בהשגחת מהדרין, בקומת הכניסה של בית חב"ד.',
    tip: "ארוחת בוקר לפני יום המקדשים ב-11.10.",
    priceThb: 250,
  },
  {
    id: "grand-palace",
    name: "הארמון המלכותי + ואט פרה קאו",
    nameEn: "Grand Palace & Wat Phra Kaew",
    region: "bangkok",
    category: "temple",
    lat: 13.75,
    lng: 100.4913,
    hook: "האתר מספר 1 בתאילנד — הבודהה הירוק וזהב עד האופק.",
    tip: "קוד לבוש נוקשה: כתפיים וברכיים מכוסות, גם לגברים. להגיע ב-8:30 בפתיחה, אחרת חום + תורים. מתעלמים מכל מי שאומר לכם ברחוב 'סגור היום' — זו הונאה קלאסית.",
    priceThb: 500,
    duration: "2-3 שעות",
  },
  {
    id: "wat-pho",
    name: "ואט פו — הבודהה השוכב",
    nameEn: "Wat Pho",
    region: "bangkok",
    category: "temple",
    lat: 13.7465,
    lng: 100.4927,
    hook: "46 מטר של בודהה זהב שוכב, ובית הספר הוותיק לעיסוי תאילנדי.",
    tip: "10 דקות הליכה מהארמון — לשלב באותו בוקר. עיסוי תאילנדי אותנטי בתוך המתחם ~480 באט לשעה.",
    priceThb: 300,
    duration: "שעה",
  },
  {
    id: "wat-arun",
    name: "ואט ארון — מקדש השחר",
    nameEn: "Wat Arun",
    region: "bangkok",
    category: "temple",
    lat: 13.7437,
    lng: 100.4889,
    hook: "הצריח שמצופה בשברי חרסינה, על גדת הצ'או פראיה.",
    tip: "הכי יפה בשקיעה מהגדה הנגדית. מעבורת מוואט פו ב-5 באט.",
    priceThb: 200,
    duration: "שעה",
  },
  {
    id: "khaosan",
    name: "רחוב קאו סאן",
    nameEn: "Khaosan Road",
    region: "bangkok",
    category: "party",
    lat: 13.759,
    lng: 100.4977,
    hook: "בירת התרמילאים בעולם. רועש, זול, קיטשי — וחובה פעם אחת.",
    tip: 'רמבוטרי הסמוך יותר נעים ופחות מטורף. הקומבינה: לישון ברמבוטרי, לצאת לקאו סאן. גם בית חב"ד ממש שם.',
    priceThb: 0,
  },
  {
    id: "chatuchak",
    name: "שוק צ'אטוצ'ק",
    nameEn: "Chatuchak Weekend Market",
    region: "bangkok",
    category: "market",
    lat: 13.7999,
    lng: 100.5502,
    hook: "15,000 דוכנים. השוק הגדול בעולם, ורק בסופ\"ש.",
    details: "פתוח שבת-ראשון בעיקר (9:00-18:00), חלקים גם בשישי בערב.",
    tip: "שימו לב — פתוח בעיקר בשבת. בטיול הזה השבתות תפוסות, אז אם רוצים שוק, ג'וד פיירס בערב הוא התחליף.",
    priceThb: 0,
    duration: "3-4 שעות",
  },
  {
    id: "jodd-fairs",
    name: "שוק לילה ג'וד פיירס",
    nameEn: "Jodd Fairs Night Market",
    region: "bangkok",
    category: "market",
    lat: 13.7566,
    lng: 100.5657,
    approx: true,
    hook: "שוק הלילה הכי חי בבנגקוק כרגע — אוכל, אורות, בירה זולה.",
    tip: 'האוכל שם לא כשר — לאכול לפני בחב"ד ולבוא בשביל האווירה והקניות. MRT לתחנת Phra Ram 9.',
    priceThb: 0,
    duration: "2-3 שעות",
  },
  {
    id: "yaowarat",
    name: "צ'יינה טאון — יאווארט",
    nameEn: "Yaowarat (Chinatown)",
    region: "bangkok",
    category: "market",
    lat: 13.7398,
    lng: 100.51,
    hook: "רחוב אחד של ניאון, קיטור ואופנועים. הכי פוטוגני בלילה.",
    tip: "הכי טוב מ-19:00. ללכת ברגל מהמעגן, לא לנסוע — התנועה שם רצח.",
    priceThb: 0,
  },
  {
    id: "golden-mount",
    name: "הר הזהב (ואט סאקט)",
    nameEn: "Wat Saket / Golden Mount",
    region: "bangkok",
    category: "viewpoint",
    lat: 13.7539,
    lng: 100.5068,
    hook: "300 מדרגות ל-360 מעלות מעל העיר העתיקה.",
    tip: "לעלות שעה לפני שקיעה. 15 דקות הליכה מקאו סאן.",
    priceThb: 100,
    duration: "שעה",
  },
  {
    id: "muay-thai",
    name: "אצטדיון מואי תאי ראג'אדמנרן",
    nameEn: "Rajadamnern Stadium",
    region: "bangkok",
    category: "party",
    lat: 13.7583,
    lng: 100.5063,
    hook: "האצטדיון הוותיק בתאילנד. קרבות אמיתיים, קהל משוגע.",
    tip: "לקנות כרטיסים אונליין (זול יותר מהקופה). היציע העליון הכי כיף — שם ההימורים והצעקות.",
    priceThb: 1200,
    duration: "3 שעות",
  },
  {
    id: "chao-phraya-boat",
    name: "סירת אקספרס בצ'או פראיה",
    nameEn: "Chao Phraya Express Boat",
    region: "bangkok",
    category: "transport",
    lat: 13.742,
    lng: 100.51,
    hook: "התחבורה הכי יפה בעיר — 16 באט וזה גם סיור נהר.",
    tip: "הדגל הכתום הוא הקו השימושי. מרציף Phra Athit (קאו סאן) עד ואט ארון/ואט פו.",
    priceThb: 16,
  },
  {
    id: "ayutthaya",
    name: "איות'איה — הבירה העתיקה",
    nameEn: "Ayutthaya",
    region: "bangkok",
    category: "temple",
    lat: 14.356,
    lng: 100.568,
    hook: "חורבות מקדשים מהמאה ה-14 וראש הבודהה בתוך שורשי העץ.",
    tip: "יום שלם. רכבת מתחנת קרונג ת'פ אפיוואט ~20 באט, ואז אופניים/טוק טוק בין האתרים. אפשרי רק אם יש לכם יום פנוי בבנגקוק.",
    priceThb: 400,
    duration: "יום שלם",
  },

  // ─────────────────────────── קופנגן ───────────────────────────
  {
    id: "chabad-phangan",
    name: 'בית חב"ד קופנגן',
    nameEn: "Chabad House Koh Phangan",
    region: "phangan",
    category: "chabad",
    lat: 9.728,
    lng: 99.965,
    approx: true,
    address: "20/18 Moo 8, Koh Phangan, Surat Thani 84280",
    phone: "+66 65 731 2561",
    hook: "בית כנסת, מסעדה ישראלית וחנות מוצרים כשרים, באזור הין קונג.",
    details:
      "פועל בעונה. בתקופות המסיבות מתמלא בישראלים, ולכן עדיף להירשם לסעודות מראש.",
    tip: "המיקום המדויק זז בין עונות — להתקשר לפני שמזמינים מונית.",
    url: "https://www.chabadthailand.com/",
  },
  {
    id: "kosher-phangan",
    name: 'מסעדה וחנות כשרה — חב"ד קופנגן',
    nameEn: "Kosher Restaurant & Market, Koh Phangan",
    region: "phangan",
    category: "kosher",
    lat: 9.728,
    lng: 99.965,
    approx: true,
    phone: "+66 65 731 2561",
    hook: "מסעדה ישראלית, ולידה מכולת עם מוצרים ישראליים ובשר כשר.",
    details:
      "החנות היא הדבר החשוב כאן — אפשר לקנות בשר כשר ומוצרים ולבשל בעצמכם.",
    tip: "שעות מוגבלות ולא כל יום. בימים שסגור — פירות מהשוק בת'ונג סאלה.",
    priceThb: 350,
  },
  {
    id: "full-moon-party",
    name: "פול מון פארטי — האד רין",
    nameEn: "Full Moon Party, Haad Rin",
    region: "phangan",
    category: "party",
    lat: 9.674,
    lng: 100.068,
    hook: "30,000 איש על חוף אחד. הירח המלא בטיול שלכם: 26.9.",
    details:
      "מתחיל בערך ב-22:00 ונמשך עד הזריחה. כניסה ~200 באט. הירח המלא נופל במוצאי שבת/חג של סוכות — כלומר אפשר לעשות את שניהם.",
    tip: "אף פעם לא לוקחים ארנק. מזומן מוגבל בכיס, בלי טלפון יקר, נעליים סגורות (זכוכית שבורה בחול), ונקודת מפגש קבועה עם החברים כי הקליטה מתה. חבל האש — לא. באמת לא.",
    priceThb: 200,
  },
  {
    id: "haad-rin",
    name: "האד רין",
    nameEn: "Haad Rin Beach",
    region: "phangan",
    category: "beach",
    lat: 9.6785,
    lng: 100.067,
    hook: "חוף המסיבה עצמו — ביום זה חוף נורמלי ויפה.",
    tip: "לישון שם רק בלילה של הפול מון. שאר הזמן זה יקר ורועש בלי סיבה.",
  },
  {
    id: "bottle-beach",
    name: "בוטל ביץ' (האד קואט)",
    nameEn: "Bottle Beach (Haad Khuat)",
    region: "phangan",
    category: "beach",
    lat: 9.796,
    lng: 100.025,
    hook: "החוף הכי יפה באי, ומגיעים אליו רק בסירה או בהליכת ג'ונגל.",
    tip: "לונגטייל מצ'אלוקלום ~150-200 באט לכיוון. הסירה האחרונה חוזרת מוקדם (בערך 16:00) — לוודא שעה עם הנהג ולא להיתקע.",
    duration: "יום",
  },
  {
    id: "secret-beach",
    name: "סיקרט ביץ' (האד סון)",
    nameEn: "Secret Beach (Haad Son)",
    region: "phangan",
    category: "beach",
    lat: 9.753,
    lng: 99.956,
    hook: "מפרץ קטן בצד המערבי — שקיעה ישר לים.",
    tip: "הגישה בכביש תלול מאוד. אם אתם לא בטוחים על הקטנוע — מונית.",
  },
  {
    id: "zen-beach",
    name: "זן ביץ' — שקיעה",
    nameEn: "Zen Beach",
    region: "phangan",
    category: "beach",
    lat: 9.742,
    lng: 99.96,
    approx: true,
    hook: "שקיעה עם מתופפים, ג'אגלרים וכל הסצנה החופשית של האי.",
    tip: "להביא בירה ומחצלת ולהגיע 45 דקות לפני השקיעה.",
    priceThb: 0,
  },
  {
    id: "than-sadet",
    name: "מפל ת'אן סאדט",
    nameEn: "Than Sadet Waterfall",
    region: "phangan",
    category: "nature",
    lat: 9.753,
    lng: 100.074,
    hook: "מפל בג'ונגל עם בריכות טבעיות לקפוץ אליהן.",
    tip: "בסוף ספטמבר יש מים — זה סוף עונת הגשמים, הכי טוב שיהיה. הכביש לשם קשה לקטנוע חלש.",
    priceThb: 0,
  },
  {
    id: "khao-ra",
    name: "קאו רא — הפסגה של האי",
    nameEn: "Khao Ra Viewpoint",
    region: "phangan",
    category: "viewpoint",
    lat: 9.748,
    lng: 100.008,
    approx: true,
    hook: "627 מטר, תצפית על כל קופנגן וסמוי ברקע.",
    tip: "עלייה של שעה-שעה וחצי בג'ונגל. לצאת ב-6:30 בבוקר לפני החום, עם 2 ליטר מים לאדם.",
    duration: "3 שעות",
  },
  {
    id: "thong-sala",
    name: "ת'ונג סאלה — עיר הנמל",
    nameEn: "Thong Sala",
    region: "phangan",
    category: "market",
    lat: 9.71,
    lng: 99.99,
    hook: "הנמל, הבנקים, הסופר והשוק הלילי (פאנטיפ).",
    tip: "פה מגיעה ויוצאת המעבורת, ופה מצטיידים לפני שנתקעים בצד השני של האי.",
  },
  {
    id: "chaloklum",
    name: "צ'אלוקלום — כפר הדייגים",
    nameEn: "Chaloklum",
    region: "phangan",
    category: "beach",
    lat: 9.79,
    lng: 100.01,
    hook: "הצפון השקט, ומכאן יוצאות הסירות לבוטל ביץ'.",
  },

  // ─────────────────────────── קוסמוי ───────────────────────────
  {
    id: "chabad-samui",
    name: 'בית חב"ד קוסמוי',
    nameEn: "Chabad of Koh Samui",
    region: "samui",
    category: "chabad",
    lat: 9.5345,
    lng: 100.062,
    approx: true,
    address: "39/8 Chaweng Beach Moo 3, Bophut, Koh Samui 84320",
    phone: "+66 77 414 180",
    hook: "בצ'אוונג ביץ' — בית כנסת, מסעדה בשרית, פיצרייה וסוכה.",
    details:
      "המרכז הישראלי של האי, וגם מקור מידע עדכני על מעבורות, מזג אוויר וחגים באזור המפרץ.",
    tip: "כאן נופל הבלוק של 2-4.10 — חמש סעודות רצופות. להירשם שבועות מראש.",
    url: "https://www.chabadthailand.com/",
  },
  {
    id: "kosher-samui",
    name: 'המסעדה הבשרית — צ\'אוונג',
    nameEn: "Meat Restaurant, Chabad Koh Samui",
    region: "samui",
    category: "kosher",
    lat: 9.5345,
    lng: 100.062,
    approx: true,
    address: "39/8 Chaweng Beach Moo 3, Bophut",
    hours: 'א\'-ה\' 12:00-22:00 · שישי 12:00-15:00 · מוצ"ש 20:00-22:30',
    hook: "בשרי כשר למהדרין בלב צ'אוונג, כולל ארוחות בוקר ישראליות.",
    tip: 'שימו לב לשעות שישי — נסגר ב-15:00, ובמוצ"ש נפתח רק ב-20:00.',
    priceThb: 400,
  },
  {
    id: "pizzeria-samui",
    name: "הפיצרייה החלבית — צ'אוונג",
    nameEn: "Dairy Pizzeria, Chabad Koh Samui",
    region: "samui",
    category: "kosher",
    lat: 9.5347,
    lng: 100.0623,
    approx: true,
    hours: 'א\'-ה\' 10:00-22:00 · שישי 10:00-15:30 · מוצ"ש 20:00-24:00',
    hook: "פיצה ומאפים חלביים, פתוחה יותר שעות מהבשרית.",
    tip: "נפתחת ב-10:00 — האופציה לארוחת בוקר לפני יום סירה.",
    priceThb: 250,
  },
  {
    id: "bakery-samui",
    name: "מאפייה ישראלית — צ'אוונג",
    nameEn: "Israeli Bakery, Chaweng",
    region: "samui",
    category: "kosher",
    lat: 9.5335,
    lng: 100.0615,
    approx: true,
    hook: "חלות לשבת, לחמים טריים, עוגות ומאפים מלוחים ומתוקים.",
    tip: "פה קונים חלות לפני הבלוק של 2-4.10. להזמין מראש — בערב חג זה נגמר.",
    priceThb: 150,
  },
  {
    id: "falafel-samui",
    name: "פלאפל וחומוס — צ'אוונג",
    nameEn: "Falafel & Hummus, Chaweng",
    region: "samui",
    category: "kosher",
    lat: 9.534,
    lng: 100.0612,
    approx: true,
    hook: "פלאפל חם, חומוס, פיתות רכות וסלטים. הכי זול והכי מהיר.",
    tip: "הפתרון לצהריים בין חוף לחוף.",
    priceThb: 180,
  },
  {
    id: "menachem-samui",
    name: "אוכל ביתי מנחם",
    nameEn: "Menachem Home Cooking",
    region: "samui",
    category: "kosher",
    lat: 9.5338,
    lng: 100.0618,
    approx: true,
    hook: "בישולים ביתיים, דגים וקציצות באווירה משפחתית.",
    tip: 'כשנמאס משניצל. עסק קטן — לאמת מיקום ושעות מול חב"ד.',
    priceThb: 300,
  },
  {
    id: "asian-kosher-samui",
    name: 'המסעדה האסייתית של חב"ד',
    nameEn: "Chabad Asian Restaurant, Samui",
    region: "samui",
    category: "kosher",
    lat: 9.5342,
    lng: 100.0625,
    approx: true,
    hook: "סושי ומוקפצים כשרים — סוף סוף אוכל אסייתי שאתם יכולים לאכול.",
    tip: "הדבר הכי קרוב לחוויה המקומית שתקבלו בכשרות. שווה ערב אחד.",
    priceThb: 450,
  },
  {
    id: "big-buddha-samui",
    name: "הבודהה הגדול (ואט פרה יאי)",
    nameEn: "Big Buddha, Wat Phra Yai",
    region: "samui",
    category: "temple",
    lat: 9.5678,
    lng: 100.06,
    hook: "12 מטר של זהב מול הים, בצפון האי.",
    tip: "הרציף ליד הוא אחת האופציות למעבורת לקופנגן. חינם, 40 דקות.",
    priceThb: 0,
  },
  {
    id: "wat-plai-laem",
    name: "ואט פלאי לאם",
    nameEn: "Wat Plai Laem",
    region: "samui",
    category: "temple",
    lat: 9.5697,
    lng: 100.045,
    hook: "אלת הרחמים ב-18 זרועות, על אגם.",
    tip: "5 דקות מהבודהה הגדול — לשלב. חינם.",
    priceThb: 0,
  },
  {
    id: "ang-thong",
    name: "פארק ימי אנג ת'ונג",
    nameEn: "Ang Thong Marine Park",
    region: "samui",
    category: "boat",
    lat: 9.62,
    lng: 99.68,
    hook: "42 איי גיר, לגונה אמרלד וקיאקים. היום הכי יפה בכל המפרץ.",
    details:
      "יוצאים בבוקר מנאת'ון או מבופוט, חוזרים אחה\"צ. כולל שנרקול, קיאק ותצפית וו-טה-לאפ.",
    tip: "הזמינו סיור עם קיאקים ולא רק ספידבוט. הפארק נסגר לפעמים בים סוער — לבדוק ערב לפני. תביאו אוכל משלכם מהמסעדה הכשרה.",
    priceThb: 1800,
    duration: "יום שלם",
  },
  {
    id: "chaweng",
    name: "חוף צ'אוונג",
    nameEn: "Chaweng Beach",
    region: "samui",
    category: "beach",
    lat: 9.535,
    lng: 100.062,
    hook: "החוף הראשי — 6 ק\"מ של חול לבן, ברים ובתי מלון.",
    tip: 'הצפון של צ\'אוונג שקט יותר, הדרום זה החיים. בית חב"ד גם הוא כאן.',
  },
  {
    id: "lamai",
    name: "חוף לאמאי",
    nameEn: "Lamai Beach",
    region: "samui",
    category: "beach",
    lat: 9.46,
    lng: 100.043,
    hook: "כמו צ'אוונג רק זול יותר ופחות מתויר.",
    tip: "אם התקציב לחוץ — לישון בלאמאי ולנסוע לצ'אוונג בקטנוע.",
  },
  {
    id: "hin-ta-hin-yai",
    name: "סלעי סבא וסבתא",
    nameEn: "Hin Ta & Hin Yai Rocks",
    region: "samui",
    category: "nature",
    lat: 9.452,
    lng: 100.049,
    hook: "שני סלעים בצורה מאוד לא צנועה. הבדיחה הכי מפורסמת באי.",
    tip: "10 דקות, חינם, בדרך ללאמאי. לא צריך יותר מזה.",
    priceThb: 0,
    duration: "20 דקות",
  },
  {
    id: "na-muang",
    name: "מפלי נא מואנג 1+2",
    nameEn: "Na Muang Waterfalls",
    region: "samui",
    category: "nature",
    lat: 9.453,
    lng: 99.98,
    hook: "מפל 1 נגיש ברגל, מפל 2 גבוה יותר ודורש טיפוס.",
    tip: "לא לקנות טיול פילים בכניסה. הליכה עצמאית למפל 2 היא 30 דקות ומגיעים לאותו מקום.",
    priceThb: 0,
  },
  {
    id: "fishermans-village",
    name: "כפר הדייגים בופוט",
    nameEn: "Fisherman's Village, Bophut",
    region: "samui",
    category: "market",
    lat: 9.56,
    lng: 100.068,
    hook: "רחוב עץ ישן עם ברים ושוק לילה בימי שישי.",
    tip: "שוק שישי נופל בטיול שלכם על ערבי חג/שבת — כדאי להגיע פשוט בערב רגיל, זה יפה גם ככה.",
  },
  {
    id: "secret-buddha-garden",
    name: "הגן הסודי של הבודהה",
    nameEn: "Secret Buddha Garden",
    region: "samui",
    category: "nature",
    lat: 9.488,
    lng: 99.995,
    approx: true,
    hook: "פסלים באמצע ג'ונגל ההרים, עם נוף לכל האי.",
    tip: "הכביש לשם הוא 4x4 בלבד — לא קטנוע ולא רכב רגיל. לקחת ג'יפ מאורגן.",
    priceThb: 80,
  },

  // ─────────────────────────── פוקט ───────────────────────────
  {
    id: "chabad-phuket",
    name: 'בית חב"ד פוקט — פאטונג',
    nameEn: "Chabad House Phuket",
    region: "phuket",
    category: "chabad",
    lat: 7.8905,
    lng: 98.299,
    approx: true,
    address: "9/6 Rat-U-Thit 200 Pee Rd, Patong, Kathu, Phuket 83150",
    phone: "+66 89 892 2353",
    hours: "א'-ה' 10:00-22:30 · שבת 10:00-23:00",
    url: "https://www.kosher-phuket.com/",
    hook: "בניין בן 4 קומות בלב פאטונג — בית כנסת, מסעדה בשרית, פיצרייה וסוכה.",
    details:
      "ליד מלון Mövenpick Myth. המרכז הישראלי של כל צד האנדמן, וגם המקום להתייעץ בו על סירות, מוניות וחדרים.",
    tip: "שימו לב שזה בפאטונג ולא בקארון. לשבת של סוכות (26.9) ולשבת בראשית (10.10) — להירשם שבועות מראש.",
  },
  {
    id: "kosher-phuket",
    name: 'המסעדה הבשרית — חב"ד פאטונג',
    nameEn: "Meat Restaurant, Chabad Phuket",
    region: "phuket",
    category: "kosher",
    lat: 7.8905,
    lng: 98.299,
    approx: true,
    address: "9/6 Rat-U-Thit 200 Pee Rd, Patong",
    phone: "+66 89 892 2353",
    hours: "א'-ה' 10:00-22:30 · שבת 10:00-23:00",
    hook: 'בשרי ישראלי בקומת הכניסה של בית חב"ד. המסעדה המרכזית באי.',
    tip: "המקום להצטייד בו לפני ימי סירה ולפני קו פי פי — לבקש מנות ארוזות.",
    priceThb: 400,
  },
  {
    id: "pizzeria-phuket",
    name: 'הפיצרייה החלבית — חב"ד פאטונג',
    nameEn: "Dairy Pizzeria, Chabad Phuket",
    region: "phuket",
    category: "kosher",
    lat: 7.8907,
    lng: 98.2993,
    approx: true,
    address: "9/6 Rat-U-Thit 200 Pee Rd, Patong",
    hook: "פיצה, פסטה ומאפים חלביים — באותו בניין של המסעדה הבשרית.",
    tip: "האופציה הזולה והמהירה. טוב לצהריים אחרי החוף.",
    priceThb: 250,
  },
  {
    id: "kosher-delivery-phuket",
    name: "משלוחים כשרים בפוקט",
    nameEn: "Kosher delivery, Phuket",
    region: "phuket",
    category: "kosher",
    lat: 7.8903,
    lng: 98.2987,
    approx: true,
    url: "https://www.kosher-phuket.com/",
    hook: 'חב"ד פוקט מביאים אוכל עד הדלת — לפאטונג ולקארון.',
    details: "~200 באט דמי משלוח, זמן הגעה 30-45 דקות לאזור פאטונג.",
    tip: "מציל אתכם בערב שאתם מתים מעייפות. אפשר גם להזמין ספיישל לשישי דרך האתר.",
    priceThb: 200,
  },
  {
    id: "patong-bangla",
    name: "פאטונג ובאנגלה רואד",
    nameEn: "Patong & Bangla Road",
    region: "phuket",
    category: "party",
    lat: 7.8925,
    lng: 98.2965,
    hook: "רחוב הלילה הכי מטורף באי. ניאון, בירה, קברטים.",
    tip: "לא הולכים אחרי אף אחד ל'שואו' בקומה שנייה — זו מלכודת חשבון קלאסית. משלמים על כל משקה כשמקבלים אותו.",
    priceThb: 0,
  },
  {
    id: "kata-beach",
    name: "חוף קטה",
    nameEn: "Kata Beach",
    region: "phuket",
    category: "beach",
    lat: 7.818,
    lng: 98.298,
    hook: "החוף המאוזן של פוקט — יפה, גלים לגלישה, פחות מטורף מפאטונג.",
    tip: "בסוף ספטמבר-אוקטובר יש גלים וזרמים באנדמן. דגל אדום = לא נכנסים. באמת.",
  },
  {
    id: "karon-beach",
    name: "חוף קארון",
    nameEn: "Karon Beach",
    region: "phuket",
    category: "beach",
    lat: 7.846,
    lng: 98.294,
    hook: 'החוף הארוך שליד בית חב"ד — הבסיס ההגיוני שלכם בפוקט.',
    tip: 'קארון זול ושקט יותר מפאטונג, אבל בית חב"ד והמסעדות הכשרות הם בפאטונג — 10 דקות בקטנוע, או משלוח ב-200 באט.',
  },
  {
    id: "big-buddha-phuket",
    name: "הבודהה הגדול של פוקט",
    nameEn: "Big Buddha Phuket",
    region: "phuket",
    category: "viewpoint",
    lat: 7.8277,
    lng: 98.312,
    hook: "45 מטר של שיש לבן על ראש ההר, עם נוף ל-360 מעלות.",
    tip: "הכביש למעלה תלול — קטנוע חלש עם שני רוכבים לא יעלה. לעלות בבוקר, בצהריים אין צל.",
    priceThb: 0,
    duration: "שעה",
  },
  {
    id: "promthep",
    name: "כף פרומטפ — שקיעה",
    nameEn: "Promthep Cape",
    region: "phuket",
    category: "viewpoint",
    lat: 7.762,
    lng: 98.305,
    hook: "נקודת השקיעה המפורסמת בפוקט, בקצה הדרומי של האי.",
    tip: "להגיע 40 דקות לפני השקיעה, אחרת אין חנייה ואין מקום. השקיעה שם באוקטובר בערך 18:15.",
    priceThb: 0,
  },
  {
    id: "phuket-old-town",
    name: "העיר העתיקה של פוקט",
    nameEn: "Phuket Old Town",
    region: "phuket",
    category: "market",
    lat: 7.884,
    lng: 98.388,
    hook: "רחובות סינו-פורטוגזיים צבעוניים, גרפיטי ובתי קפה.",
    tip: "שוק הליכה בתלאנג רואד בימי ראשון בערב — 11.10 זה יום הטיסה, אז אולי 4.10 בערב אחרי החג.",
    priceThb: 0,
    duration: "3 שעות",
  },
  {
    id: "phang-nga",
    name: "מפרץ פאנג נגה + אי ג'יימס בונד",
    nameEn: "Phang Nga Bay & James Bond Island",
    region: "phuket",
    category: "boat",
    lat: 8.274,
    lng: 98.501,
    hook: "צוקי גיר שיוצאים מהמים, מערות ים וקיאקים בין המונוליתים.",
    tip: "לבחור סיור לונגטייל קטן ולא ספידבוט ענק של 100 איש. יוצאים מוקדם בבוקר כדי להקדים את הקבוצות.",
    priceThb: 1500,
    duration: "יום שלם",
  },
  {
    id: "wat-chalong",
    name: "ואט צ'אלונג",
    nameEn: "Wat Chalong",
    region: "phuket",
    category: "temple",
    lat: 7.846,
    lng: 98.337,
    hook: "המקדש החשוב בפוקט, עם צ'די בן שלוש קומות.",
    tip: "חינם, בדרך מקארון לעיר העתיקה. חצי שעה מספיקה.",
    priceThb: 0,
  },
  {
    id: "freedom-beach",
    name: "פרידום ביץ'",
    nameEn: "Freedom Beach",
    region: "phuket",
    category: "beach",
    lat: 7.869,
    lng: 98.276,
    hook: "חוף חול לבן מוסתר, מגיעים אליו בלונגטייל מפאטונג.",
    tip: "~1500 באט לסירה הלוך-חזור, מתחלקים בין כולם. לסכם שעת איסוף מראש ולשלם רק בחזרה.",
  },
  {
    id: "similan-closed",
    name: "איי סימילן — סגורים",
    nameEn: "Similan Islands (closed)",
    region: "phuket",
    category: "boat",
    lat: 8.657,
    lng: 97.645,
    hook: "העונה נפתחת רק ב-15 באוקטובר — אחרי הטיסה שלכם הביתה.",
    details:
      "הפארק הלאומי סגור לתיירים במאי-אוקטובר. אם מישהו מוכר לכם שם סיור לסימילן בתאריכים האלה — זו הונאה.",
    tip: "התחליף באזור: פאנג נגה או האיים סביב פי פי.",
  },

  // ─────────────────────────── קו פי פי ───────────────────────────
  {
    id: "tonsai-village",
    name: "כפר טונסאי",
    nameEn: "Tonsai Village",
    region: "phiphi",
    category: "party",
    lat: 7.74,
    lng: 98.775,
    hook: "כל האי במרחק הליכה: סמטאות, ברים, בקטים ומסיבות חוף.",
    tip: "אין מכוניות באי. מזומן — יש כספומטים אבל עם עמלה גבוהה, עדיף למשוך בפוקט.",
  },
  {
    id: "phiphi-viewpoint",
    name: "תצפית פי פי",
    nameEn: "Phi Phi Viewpoint",
    region: "phiphi",
    category: "viewpoint",
    lat: 7.744,
    lng: 98.779,
    hook: "התמונה של תאילנד: שני מפרצים ורצועת חול אחת ביניהם.",
    tip: "30 דקות מדרגות. לעלות בזריחה (5:45) או שעה לפני שקיעה — בצהריים זה תנור.",
    priceThb: 30,
    duration: "שעתיים",
  },
  {
    id: "maya-bay",
    name: "מאיה ביי",
    nameEn: "Maya Bay",
    region: "phiphi",
    category: "boat",
    lat: 7.678,
    lng: 98.766,
    hook: 'המפרץ מ"החוף" עם לאונרדו. נפתח מחדש אחרי שיקום השונית.',
    details:
      "אסור לשחות במפרץ עצמו, ויש מכסת מבקרים. נכנסים דרך רציף בצד האחורי.",
    tip: "לצאת בסיור זריחה (6:00) — מגיעים לפני כל הסירות מפוקט ורואים אותו כמעט ריק.",
    priceThb: 400,
  },
  {
    id: "bamboo-island",
    name: "אי הבמבוק",
    nameEn: "Bamboo Island",
    region: "phiphi",
    category: "beach",
    lat: 7.833,
    lng: 98.814,
    hook: "חול לבן ומים תכולים בלי כלום מסביב. הכי קרוב לגלויה.",
    tip: "חלק מרוב סיורי היום. השנרקול סביבו טוב יותר מבמאיה ביי.",
    priceThb: 400,
  },
  {
    id: "long-beach-phiphi",
    name: "לונג ביץ'",
    nameEn: "Long Beach (Hat Yao)",
    region: "phiphi",
    category: "beach",
    lat: 7.729,
    lng: 98.776,
    hook: "שקט יחסית לטונסאי, עם שונית לשנרקול ישר מהחוף.",
    tip: "טקסי-בוט מטונסאי ~150 באט, או 30 דקות הליכה בשפל.",
  },
  {
    id: "phiphi-no-kosher",
    name: "אין כשרות בפי פי",
    nameEn: "No kosher on Phi Phi",
    region: "phiphi",
    category: "kosher",
    lat: 7.7405,
    lng: 98.7765,
    hook: 'האי היחיד במסלול בלי בית חב"ד ובלי מסעדה כשרה.',
    details:
      'בית חב"ד הקרוב הוא בקראבי/אאו נאנג ביבשת, או בפוקט. לתכנן את פי פי כאמצע שבוע בלבד.',
    tip: "להביא מפוקט: טונה, קרקרים, חמאת בוטנים, נודלס כשרים ופירות. בסופר של טונסאי יש פירות ומים.",
  },
  {
    id: "chabad-krabi",
    name: 'בית חב"ד קראבי / אאו נאנג',
    nameEn: "Chabad Krabi (Ao Nang)",
    region: "phiphi",
    category: "chabad",
    lat: 8.032,
    lng: 98.825,
    approx: true,
    hook: 'החב"ד הקרוב לפי פי — ביבשת, שעה וחצי במעבורת.',
    tip: "רלוונטי רק אם אתם משנים מסלול ועוברים דרך קראבי. לוודא שהוא פעיל בעונה.",
    url: "https://www.chabadthailand.com/",
  },

  // ─────────────────── תחבורה בין האזורים ───────────────────
  {
    id: "ferry-samui-phangan",
    name: "מעבורת סמוי ↔ קופנגן",
    nameEn: "Samui ↔ Phangan Ferry",
    region: "samui",
    category: "transport",
    lat: 9.5678,
    lng: 100.062,
    hook: "30-45 דקות בין האיים. לומפראיה / סונגסרם, כמה יציאות ביום.",
    tip: "מרציף הבודהה הגדול או נאת'ון. ~300-400 באט. להזמין יום מראש בעונה, ולא לתכנן מעבורת אחרונה בערב חג.",
    priceThb: 350,
  },
  {
    id: "samui-airport",
    name: "נמל התעופה קוסמוי (USM)",
    nameEn: "Koh Samui Airport",
    region: "samui",
    category: "transport",
    lat: 9.5479,
    lng: 100.0622,
    hook: "שדה גן פתוח וחמוד — וגם היקר בתאילנד (בנגקוק אייר).",
    tip: "חלופה זולה: טיסה לסוראט ת'אני + אוטובוס+מעבורת. מוסיף 4-5 שעות וחוסך הרבה.",
  },
  {
    id: "phuket-airport",
    name: "נמל התעופה פוקט (HKT)",
    nameEn: "Phuket Airport",
    region: "phuket",
    category: "transport",
    lat: 8.1132,
    lng: 98.3169,
    hook: "השדה הגדול של הדרום, שעה מקארון.",
    tip: "מיניבוס משותף ~200 באט, גראב ~700-900. להזמין גראב מחוץ לטרמינל — בפנים המוניות מאורגנות ויקרות.",
  },
  {
    id: "rassada-pier",
    name: "רציף ראסאדה — מעבורת לפי פי",
    nameEn: "Rassada Pier",
    region: "phuket",
    category: "transport",
    lat: 7.8797,
    lng: 98.4083,
    hook: "מכאן יוצאות המעבורות לקו פי פי, ~2 שעות.",
    tip: "יציאות בערך 8:30 / 11:00 / 14:30. ~450 באט. בים סוער באוקטובר לפעמים מבטלים — לשמור יום גמישות.",
    priceThb: 450,
  },
  {
    id: "bkk-airport",
    name: "סוברנבומי (BKK)",
    nameEn: "Suvarnabhumi Airport",
    region: "bangkok",
    category: "transport",
    lat: 13.69,
    lng: 100.7501,
    hook: "שדה הנחיתה מישראל, 30 ק\"מ ממרכז בנגקוק.",
    tip: "רכבת ה-ARL עד פאיה תאי ואז מונית/BTS, או גראב ישר לקאו סאן (~400 באט). לא לוקחים מונית שמסרבת למונה.",
  },
  {
    id: "don-mueang",
    name: "דון מואנג (DMK)",
    nameEn: "Don Mueang Airport",
    region: "bangkok",
    category: "transport",
    lat: 13.9126,
    lng: 100.6068,
    hook: "שדה הלואו-קוסט — מכאן טסים לרוב לסמוי דרך סוראט ת'אני, ולפוקט.",
    tip: "המעבר בין BKK ל-DMK הוא שעה-שעתיים בפקק. אף פעם לא לתכנן קונקשן קצר ביניהם.",
  },

  // ═══════════ פוקט — תוספות ═══════════
  {
    id: "kosher-takeaway-phuket",
    name: "ארוחות ארוזות מבית חב\"ד פוקט",
    nameEn: "Kosher take-away, Chabad Phuket",
    region: "phuket",
    category: "kosher",
    lat: 7.8913,
    lng: 98.2984,
    approx: true,
    hook: "הפתרון לימי סירה ולפי פי — מזמינים ערב לפני ולוקחים בבוקר.",
    details:
      "בתי חב\"ד בתאילנד מכינים חבילות אוכל ארוזות למי שיוצא לסיור יום. צריך להזמין מראש, בדרך כלל עד הערב שלפני.",
    tip: "להזמין ביחד עם עוד חבר'ה — כמות גדולה יותר מקבלים יותר בקלות. לבקש גם בקבוקי מים.",
    priceThb: 250,
  },
  {
    id: "kosher-shop-phuket",
    name: "מוצרים ארוזים בהכשר — וילה מרקט / טופס",
    nameEn: "Imported kosher-certified groceries",
    region: "phuket",
    category: "kosher",
    lat: 7.819,
    lng: 98.297,
    approx: true,
    hook: "רשתות המזון המיובא בפוקט — שם נמצאים המוצרים עם ההכשרים.",
    details:
      "Villa Market ו-Tops מחזיקות מוצרים מיובאים מארה\"ב ומאירופה. חלקם נושאים OU / OK / Kof-K.",
    tip: "לא כל מה שמיובא כשר — לבדוק סמל הכשר על האריזה עצמה, לא להסתמך על המותג. טונה, קטניות בקופסה, חלב שקדים, קרקרים וממרחים זה מה שהכי קל למצוא.",
  },
  {
    id: "rawai-fish-market",
    name: "שוק הדגים ראוואי",
    nameEn: "Rawai Seafood Market",
    region: "phuket",
    category: "market",
    lat: 7.773,
    lng: 98.326,
    hook: "שוק דגים טרי על החוף, בדרום האי.",
    details:
      "אפשר לקנות דגים טריים ישירות מהדייגים. מבחינת כשרות: רק דגים עם סנפיר וקשקשת, וההכנה חייבת להיות שלכם.",
    tip: "המסעדות מסביב יבשלו לכם את מה שקניתם — אבל זה מטבח לא כשר. לקנות דג בלבד ולהתייעץ בחב\"ד מה אפשר לעשות איתו.",
    priceThb: 300,
  },
  {
    id: "karon-viewpoint",
    name: "תצפית קארון (שלושת החופים)",
    nameEn: "Karon Viewpoint",
    region: "phuket",
    category: "viewpoint",
    lat: 7.7838,
    lng: 98.305,
    hook: "קטה נוי, קטה וקארון בפריים אחד. התצפית הכי מצולמת באי.",
    tip: "בדרך לפרומטפ — לעצור בשתיהן באותה נסיעה. חינם, יש חנייה.",
    priceThb: 0,
    duration: "20 דקות",
  },
  {
    id: "nai-harn",
    name: "חוף נאי הרן",
    nameEn: "Nai Harn Beach",
    region: "phuket",
    category: "beach",
    lat: 7.777,
    lng: 98.3033,
    hook: "החוף האהוב על המקומיים — פחות מלונות, יותר עצים ואגם מאחור.",
    tip: "הכי טוב בבוקר. יש שם גם בריכות טבעיות בסלעים בקצה הדרומי.",
  },
  {
    id: "ya-nui",
    name: "חוף יא נוי",
    nameEn: "Ya Nui Beach",
    region: "phuket",
    category: "beach",
    lat: 7.769,
    lng: 98.299,
    hook: "מפרץ קטן בין סלעים, ממש מתחת לתצפית טחנת הרוח.",
    tip: "השנרקול הכי נוח בפוקט — נכנסים ישר מהחוף. להשכיר מסכה 100 באט במקום.",
  },
  {
    id: "windmill-viewpoint",
    name: "תצפית טחנת הרוח",
    nameEn: "Windmill Viewpoint",
    region: "phuket",
    category: "viewpoint",
    lat: 7.771,
    lng: 98.2985,
    hook: "הכביש בין נאי הרן לפרומטפ, עם נוף לים מכל הכיוונים.",
    tip: "עוצרים בדרך. שקיעה מכאן טובה כמעט כמו מפרומטפ ובלי ההמון.",
    priceThb: 0,
  },
  {
    id: "kata-noi",
    name: "קטה נוי",
    nameEn: "Kata Noi Beach",
    region: "phuket",
    category: "beach",
    lat: 7.808,
    lng: 98.296,
    hook: "אחות קטנה ושקטה של קטה, מעבר לגבעה.",
    tip: "החול הכי לבן באזור. בסוף אוקטובר יש שם גלים — נחמד לגלישה, פחות לשחייה.",
  },
  {
    id: "kamala",
    name: "חוף קמאלה",
    nameEn: "Kamala Beach",
    region: "phuket",
    category: "beach",
    lat: 7.954,
    lng: 98.281,
    hook: "צפונית לפאטונג — משפחתי, רגוע, ושקיעות מצוינות.",
    tip: "20 דקות בקטנוע מפאטונג. הקצה הצפוני של החוף כמעט ריק.",
  },
  {
    id: "surin-laemsing",
    name: "סורין ולאם סינג",
    nameEn: "Surin & Laem Sing Beaches",
    region: "phuket",
    category: "beach",
    lat: 7.978,
    lng: 98.277,
    hook: "שני חופים צמודים בצפון — לאם סינג מוסתר בין סלעים ושווה את ההליכה.",
    tip: "לאם סינג: חונים בכביש ויורדים במדרגות 5 דקות. אין שירותים, להביא מים.",
  },
  {
    id: "banana-beach",
    name: "בננה ביץ'",
    nameEn: "Banana Beach",
    region: "phuket",
    category: "beach",
    lat: 8.033,
    lng: 98.276,
    hook: "מפרץ קטן ומוסתר בצפון-מערב, עם שונית קרובה לחוף.",
    tip: "הירידה היא שביל בג'ונגל של 10 דקות. לבוא לפני 10:00 — אחר כך מגיעים הטיולים.",
  },
  {
    id: "coral-island",
    name: "האי האלמוגי (קו הֵי)",
    nameEn: "Coral Island (Koh Hey)",
    region: "phuket",
    category: "boat",
    lat: 7.716,
    lng: 98.363,
    hook: "15 דקות בספידבוט מצ'אלונג — מים תכולים ושנרקול טוב.",
    tip: "יום סירה קצר ליום שלא רוצים לצאת מוקדם. אפשר גם רק חצי יום.",
    priceThb: 1000,
    duration: "חצי יום",
  },
  {
    id: "racha-island",
    name: "קו ראצ'ה יאי",
    nameEn: "Racha Yai Island",
    region: "phuket",
    category: "boat",
    lat: 7.607,
    lng: 98.363,
    hook: "מים הכי צלולים באזור פוקט. אתר צלילה וגם שנרקול מצוין.",
    tip: "שעה בספידבוט. באוקטובר לבדוק תחזית ים — הסיור מתבטל בגלים.",
    priceThb: 1600,
    duration: "יום",
  },
  {
    id: "phuket-elephant-sanctuary",
    name: "מקלט הפילים של פוקט",
    nameEn: "Phuket Elephant Sanctuary",
    region: "phuket",
    category: "nature",
    lat: 8.033,
    lng: 98.363,
    hook: "מקלט אמיתי לפילים מנוצלים — צופים ומאכילים, לא רוכבים.",
    details:
      "פילים שהוצאו מתעשיית הרכיבה והכריתה. אין רכיבה ואין מופעים, ולכן זה גם באמת אתי.",
    tip: "להזמין שבוע מראש, מתמלא. כל מקום שמציע רכיבה על פיל — לא ללכת לשם. זו התעללות.",
    priceThb: 3000,
    duration: "חצי יום",
  },
  {
    id: "khao-rang",
    name: "גבעת קאו ראנג",
    nameEn: "Khao Rang Viewpoint",
    region: "phuket",
    category: "viewpoint",
    lat: 7.89,
    lng: 98.3805,
    hook: "תצפית על העיר העתיקה ועל המפרץ — הכי יפה בשקיעה.",
    tip: "5 דקות מהעיר העתיקה. לשלב עם ערב בסוי רומני.",
    priceThb: 0,
  },
  {
    id: "soi-romanee",
    name: "סוי רומני",
    nameEn: "Soi Romanee",
    region: "phuket",
    category: "market",
    lat: 7.8843,
    lng: 98.3888,
    hook: "הרחוב הכי צבעוני בעיר העתיקה — בתים סינו-פורטוגזיים ופנסים.",
    tip: "הכי יפה בשעה שלפני החשכה. שם גם רוב בתי הקפה והגרפיטי.",
    priceThb: 0,
  },
  {
    id: "naka-market",
    name: "שוק נאקה (שוק סופ\"ש)",
    nameEn: "Naka Weekend Market",
    region: "phuket",
    category: "market",
    lat: 7.877,
    lng: 98.381,
    hook: "השוק הגדול של פוקט — שבת וראשון בערב, ליד העיר העתיקה.",
    tip: "בטיול שלכם רק ראשון 27.9 או 4.10 רלוונטיים. מזומן בלבד.",
    priceThb: 0,
  },
  {
    id: "malin-plaza",
    name: "שוק לילה מאלין פלאזה",
    nameEn: "Malin Plaza Night Market",
    region: "phuket",
    category: "market",
    lat: 7.888,
    lng: 98.2985,
    hook: "שוק לילה בלב פאטונג, כל ערב.",
    tip: "האוכל שם לא כשר — אבל המסעדה הכשרה של חב\"ד היא באותו אזור, ממש בקרבת מקום. לאכול קודם ואז לבוא לשוק.",
    priceThb: 0,
  },
  {
    id: "bangla-boxing",
    name: "אצטדיון באנגלה בוקסינג",
    nameEn: "Bangla Boxing Stadium",
    region: "phuket",
    category: "party",
    lat: 7.893,
    lng: 98.2995,
    hook: "מואי תאי אמיתי בלב פאטונג, כמה ערבים בשבוע.",
    tip: "כרטיסים אונליין זולים מהרחוב. היציע הרגיל מספיק — הרינגסייד לא שווה את ההפרש.",
    priceThb: 1700,
    duration: "3 שעות",
  },
  {
    id: "kathu-waterfall",
    name: "מפל קאתו",
    nameEn: "Kathu Waterfall",
    region: "phuket",
    category: "nature",
    lat: 7.913,
    lng: 98.339,
    hook: "מפל בג'ונגל 20 דקות מפאטונג, עם בריכות לטבילה.",
    tip: "בסוף ספטמבר יש מים — זה בדיוק הזמן. נעליים עם אחיזה, הסלעים חלקלקים.",
    priceThb: 0,
    duration: "שעתיים",
  },

  // ═══════════ קוסמוי — תוספות ═══════════
  {
    id: "kosher-takeaway-samui",
    name: "ארוחות ארוזות מבית חב\"ד סמוי",
    nameEn: "Kosher take-away, Chabad Samui",
    region: "samui",
    category: "kosher",
    lat: 9.533,
    lng: 100.062,
    approx: true,
    hook: "ליום השייט באנג ת'ונג ולימים שיוצאים מוקדם.",
    tip: "להזמין ערב לפני. ביום של אנג ת'ונג זה ההבדל בין לאכול ללא לאכול — על הסירה אין שום דבר בשבילכם.",
    priceThb: 250,
  },
  {
    id: "kosher-shop-samui",
    name: "מוצרים ארוזים בהכשר — צ'אוונג",
    nameEn: "Imported kosher-certified groceries, Chaweng",
    region: "samui",
    category: "kosher",
    lat: 9.531,
    lng: 100.06,
    approx: true,
    hook: "סופרים עם מזון מיובא בצ'אוונג ובלאמאי.",
    details:
      "Tops ו-Villa Market מחזיקות מוצרים מיובאים; חלקם עם OU / OK / Kof-K.",
    tip: "כאן מצטיידים לפני הבלוק של שלושת ימי החג ב-2-4.10. לבדוק סמל הכשר על כל אריזה בנפרד.",
  },
  {
    id: "choeng-mon",
    name: "חוף צ'ואנג מון",
    nameEn: "Choeng Mon Beach",
    region: "samui",
    category: "beach",
    lat: 9.572,
    lng: 100.064,
    hook: "מפרץ רדוד ושקט בצפון-מזרח, עם אי קטן שאפשר ללכת אליו בשפל.",
    tip: "10 דקות מצ'אוונג וכמעט ריק. הכי טוב לבוקר עצלן.",
  },
  {
    id: "silver-beach",
    name: "סילבר ביץ' (קריסטל ביי)",
    nameEn: "Silver Beach (Crystal Bay)",
    region: "samui",
    category: "beach",
    lat: 9.479,
    lng: 100.062,
    hook: "מפרץ קטן בין סלעי גרניט, בין צ'אוונג ללאמאי. המים הכי צלולים באי.",
    tip: "שנרקול טוב ישר מהחוף. חנייה מוגבלת — לבוא מוקדם.",
  },
  {
    id: "maenam",
    name: "חוף מאנם",
    nameEn: "Maenam Beach",
    region: "samui",
    category: "beach",
    lat: 9.572,
    lng: 99.98,
    hook: "החוף הארוך והזול בצפון, עם נוף לקופנגן.",
    tip: "פה גם השוק הלילי של מאנם בערבי חמישי. אזור טוב ללינה זולה.",
  },
  {
    id: "taling-ngam",
    name: "טאלינג נגאם — הצד המערבי",
    nameEn: "Taling Ngam (West Coast)",
    region: "samui",
    category: "beach",
    lat: 9.439,
    lng: 99.942,
    hook: "הצד שאף אחד לא מגיע אליו — שקיעות ישר לים ואפס תיירים.",
    tip: "45 דקות מצ'אוונג בקטנוע. אין שם כמעט כלום, וזה בדיוק העניין.",
  },
  {
    id: "chaweng-noi",
    name: "צ'אוונג נוי",
    nameEn: "Chaweng Noi Beach",
    region: "samui",
    category: "beach",
    lat: 9.515,
    lng: 100.066,
    hook: "המפרץ הקטן מדרום לצ'אוונג, מעבר לגבעה.",
    tip: "5 דקות מהרעש של צ'אוונג ופתאום שקט.",
  },
  {
    id: "lad-koh-viewpoint",
    name: "תצפית לאד קו",
    nameEn: "Lad Koh Viewpoint",
    region: "samui",
    category: "viewpoint",
    lat: 9.503,
    lng: 100.068,
    hook: "התצפית על הכביש הטבעתי בין צ'אוונג ללאמאי.",
    tip: "עוצרים בדרך. חינם, ויש שם דוכן שתייה.",
    priceThb: 0,
  },
  {
    id: "wat-khunaram",
    name: "ואט קונאראם — הנזיר החנוט",
    nameEn: "Wat Khunaram (Mummified Monk)",
    region: "samui",
    category: "temple",
    lat: 9.465,
    lng: 99.988,
    hook: "נזיר שנפטר במדיטציה ב-1973 ומוצג מאז בוויטרינה, עם משקפי שמש.",
    tip: "מוזר ומרתק. חינם, 15 דקות, על הכביש הטבעתי בדרך למפלים.",
    priceThb: 0,
  },
  {
    id: "red-temple-samui",
    name: "המקדש האדום (ואט ראצ'אתמאראם)",
    nameEn: "Wat Ratchathammaram (Red Temple)",
    region: "samui",
    category: "temple",
    lat: 9.448,
    lng: 100.062,
    hook: "מקדש אדום-זהב מול הים בלאמאי. הכי פוטוגני באי.",
    tip: "חינם. הכי יפה בשעה הראשונה אחרי הזריחה או לפני השקיעה.",
    priceThb: 0,
  },
  {
    id: "overlap-stone",
    name: "אוברלאפ סטון",
    nameEn: "Overlap Stone Viewpoint",
    region: "samui",
    category: "viewpoint",
    lat: 9.452,
    lng: 100.025,
    hook: "סלע ענק מאוזן על סלע אחר, עם נוף לכל דרום האי.",
    tip: "הכביש למעלה תלול. יש בית קפה בפסגה עם הנוף הכי טוב באי.",
    priceThb: 50,
  },
  {
    id: "hin-lad",
    name: "מפל הין לאד",
    nameEn: "Hin Lad Waterfall",
    region: "samui",
    category: "nature",
    lat: 9.509,
    lng: 99.949,
    hook: "הליכה של 20 דקות בג'ונגל עד בריכה טבעית, ליד נאת'ון.",
    tip: "פחות מוכר מנא מואנג ולכן ריק. נעליים סגורות.",
    priceThb: 0,
    duration: "שעתיים",
  },
  {
    id: "pig-island",
    name: "אי החזירים (קו מדסום)",
    nameEn: "Pig Island (Koh Madsum)",
    region: "samui",
    category: "boat",
    lat: 9.39,
    lng: 99.988,
    hook: "אי קטן בדרום עם חזירים שמסתובבים על החוף ושנרקול טוב.",
    tip: "חצי יום בלונגטייל מת'ונג קרוט. אלטרנטיבה קלה לאנג ת'ונג ליום עייף.",
    priceThb: 1200,
    duration: "חצי יום",
  },
  {
    id: "samui-elephant-sanctuary",
    name: "מקלט הפילים של סמוי",
    nameEn: "Samui Elephant Sanctuary",
    region: "samui",
    category: "nature",
    lat: 9.539,
    lng: 100.033,
    hook: "מקלט ללא רכיבה — צופים, מאכילים, והפילים חופשיים.",
    tip: "להזמין מראש. לא ללכת לשום מקום שמציע רכיבה על פילים.",
    priceThb: 3000,
    duration: "חצי יום",
  },
  {
    id: "chaweng-walking-street",
    name: "צ'אוונג ווקינג סטריט",
    nameEn: "Chaweng Walking Street",
    region: "samui",
    category: "market",
    lat: 9.534,
    lng: 100.061,
    hook: "שוק לילה בלב צ'אוונג — בגדים, מזכרות, קעקועי חינה.",
    tip: "מתחיל ~17:00. לבוא אחרי שאכלתם — האוכל שם לא כשר.",
    priceThb: 0,
  },
  {
    id: "lamai-night-plaza",
    name: "לאמאי נייט פלאזה",
    nameEn: "Lamai Night Plaza",
    region: "samui",
    category: "market",
    lat: 9.468,
    lng: 100.047,
    hook: "השוק והברים של לאמאי, כל ערב.",
    tip: "זול יותר מצ'אוונג ופחות דוחף. יש שם גם זירת מואי תאי.",
    priceThb: 0,
  },
  {
    id: "coco-tams",
    name: "קוקו טאמס — בופוט",
    nameEn: "Coco Tam's, Bophut",
    region: "samui",
    category: "party",
    lat: 9.561,
    lng: 100.068,
    hook: "בר חוף עם נדנדות במים ומופע אש בערב. הכי מפורסם בסמוי.",
    tip: "לבוא לשקיעה בשביל הנדנדות. משקאות יקרים — לשתות אחד ולהישאר לאווירה.",
    priceThb: 350,
  },
  {
    id: "nathon",
    name: "נאת'ון — נמל האי",
    nameEn: "Nathon Town & Pier",
    region: "samui",
    category: "transport",
    lat: 9.539,
    lng: 99.937,
    hook: "העיר האמיתית של סמוי, ומכאן יוצאות המעבורות ליבשת.",
    tip: "בשוק המקומי שם הפירות הכי זולים באי. גם הרציף העיקרי לסוראט ת'אני.",
  },

  // ═══════════ קופנגן — תוספות ═══════════
  {
    id: "thong-nai-pan",
    name: "ת'ונג נאי פאן",
    nameEn: "Thong Nai Pan",
    region: "phangan",
    category: "beach",
    lat: 9.781,
    lng: 100.064,
    hook: "שני מפרצי חול לבן בצפון-מזרח. הצד היפה והשקט של האי.",
    tip: "הכביש לשם עבר שיפוץ ועכשיו נוסע — אבל עדיין תלול בקטעים. אם הקטנוע חלש, סונגתאו מת'ונג סאלה.",
  },
  {
    id: "haad-salad",
    name: "האד סאלאד",
    nameEn: "Haad Salad",
    region: "phangan",
    category: "beach",
    lat: 9.772,
    lng: 99.96,
    hook: "מפרץ מוגן בצפון-מערב עם שונית קרובה — שנרקול מהחוף.",
    tip: "אחד המעטים שאפשר לשחות בו גם בשפל. שקיעה מצוינת.",
  },
  {
    id: "haad-yao",
    name: "האד יאו",
    nameEn: "Haad Yao",
    region: "phangan",
    category: "beach",
    lat: 9.762,
    lng: 99.957,
    hook: "החוף הארוך במערב — רדוד, רגוע, ומלא ברים על החול.",
    tip: "הבסיס הכי נוח למי שלא רוצה את המסיבות של האד רין. שקיעה כל ערב.",
  },
  {
    id: "mae-haad-koh-ma",
    name: "מאה האד וקו מא",
    nameEn: "Mae Haad & Koh Ma",
    region: "phangan",
    category: "beach",
    lat: 9.796,
    lng: 99.977,
    hook: "רצועת חול שנחשפת בשפל ומחברת את החוף לאי קטן. השנרקול הכי טוב באי.",
    details:
      "קו מא הוא שמורה ימית — שונית חיה ממש מהחוף, בלי צורך בסירה.",
    tip: "לבוא בשפל כדי ללכת ברגל. להשכיר מסכה בחוף ~100 באט, ולא לדרוך על האלמוגים.",
    priceThb: 0,
  },
  {
    id: "haad-khom",
    name: "האד קום (מפרץ האלמוגים)",
    nameEn: "Haad Khom (Coral Bay)",
    region: "phangan",
    category: "beach",
    lat: 9.793,
    lng: 100.001,
    hook: "מפרץ קטן ליד צ'אלוקלום, עם אלמוגים ודגים ממש בכניסה למים.",
    tip: "בדרך לבוטל ביץ' — לעצור. כמעט ריק בבקרים.",
  },
  {
    id: "haad-yuan",
    name: "האד יואן",
    nameEn: "Haad Yuan",
    region: "phangan",
    category: "beach",
    lat: 9.687,
    lng: 100.074,
    hook: "מפרץ מבודד צפונית להאד רין — מגיעים רק בטקסי-בוט או בהליכת ג'ונגל.",
    tip: "לונגטייל מהאד רין ~150 באט. המקום להתאושש בו אחרי לילה בהאד רין.",
    priceThb: 150,
  },
  {
    id: "phaeng-domsila",
    name: "מפל פאנג ותצפית דומסילה",
    nameEn: "Phaeng Waterfall & Domsila Viewpoint",
    region: "phangan",
    category: "nature",
    lat: 9.742,
    lng: 100.017,
    hook: "מפל בפארק הלאומי, ומעליו טיפוס קצר לתצפית על כל דרום האי.",
    tip: "הכניסה חינם. מהמפל לדומסילה זה 30 דקות טיפוס עם חבלים — נעליים סגורות.",
    priceThb: 0,
    duration: "שעתיים",
  },
  {
    id: "wang-sai",
    name: "מפל וואנג סאי",
    nameEn: "Wang Sai Waterfall",
    region: "phangan",
    category: "nature",
    lat: 9.753,
    lng: 99.962,
    hook: "מפל קטן במערב עם בריכות טבעיות, קרוב להאד יאו.",
    tip: "הכי טוב בסוף עונת הגשמים — כלומר בדיוק עכשיו. בעונה יבשה זה כמעט ריק.",
    priceThb: 0,
  },
  {
    id: "wat-phu-khao-noi",
    name: "ואט פו קאו נוי",
    nameEn: "Wat Phu Khao Noi",
    region: "phangan",
    category: "temple",
    lat: 9.706,
    lng: 100.009,
    hook: "המקדש העתיק באי, על גבעה מעל ת'ונג סאלה.",
    tip: "חינם, 20 דקות, ונוף יפה מלמעלה. כתפיים וברכיים מכוסות.",
    priceThb: 0,
  },
  {
    id: "wat-pho-sauna",
    name: "סאונת הצמחים של ואט פו",
    nameEn: "Wat Pho Herbal Sauna",
    region: "phangan",
    category: "nature",
    lat: 9.696,
    lng: 100.0,
    approx: true,
    hook: "סאונה תאילנדית בניהול נזירים, בתוך מקדש. 100 באט.",
    tip: "החוויה הכי מקומית באי, ובדיוק מה שצריך אחרי יום קטנוע. סגור בחלק מהימים — לבדוק לפני.",
    priceThb: 100,
  },
  {
    id: "amsterdam-bar",
    name: "אמסטרדם בר — שקיעה",
    nameEn: "Amsterdam Bar",
    region: "phangan",
    category: "party",
    lat: 9.701,
    lng: 99.966,
    hook: "בר על ראש גבעה בדרום-מערב, עם הנוף הכי פתוח לשקיעה באי.",
    tip: "להגיע שעה לפני. הכביש האחרון תלול מאוד — לרדת ברגל אם לא בטוחים.",
    priceThb: 150,
  },
  {
    id: "sunset-hill",
    name: "סאנסט היל / 360 בר",
    nameEn: "Sunset Hill / Three Sixty Bar",
    region: "phangan",
    category: "viewpoint",
    lat: 9.748,
    lng: 99.96,
    approx: true,
    hook: "תצפית מעל האד יאו — הים משני הצדדים והשמש נכנסת בדיוק באמצע.",
    tip: "אלטרנטיבה נגישה יותר מאמסטרדם. נחמד גם בלי לשתות.",
  },
  {
    id: "jungle-experience",
    name: "ג'אנגל אקספיריאנס",
    nameEn: "Jungle Experience Party",
    region: "phangan",
    category: "party",
    lat: 9.73,
    lng: 100.01,
    approx: true,
    hook: "מסיבת ג'ונגל אמיתית בבאן טאי, פעמיים בחודש. הרבה יותר טובה מהפול מון.",
    details:
      "התאריכים נקבעים סביב מחזור הירח ומתפרסמים באי ובעמודי הפייסבוק שלהם.",
    tip: "בתאריכים שלכם בקופנגן (4-6.10) יש סיכוי טוב שאחת רצה — לבדוק על האי כשמגיעים. סונגתאו הלוך-חזור, לא קטנוע.",
    priceThb: 500,
  },
  {
    id: "half-moon",
    name: "האף מון פסטיבל",
    nameEn: "Half Moon Festival",
    region: "phangan",
    category: "party",
    lat: 9.725,
    lng: 100.021,
    approx: true,
    hook: "מסיבת יער בחצי ירח — הפקה גדולה, קהל קטן יותר מהפול מון.",
    details:
      "הירח המלא נפל ב-26.9, ולכן בתאריכים שלכם (4-6.10) חצי הירח הוא מה שרלוונטי.",
    tip: "כרטיסים נמכרים מראש באי ובאונליין. לבדוק תאריך מדויק כשמגיעים — הוא זז.",
    priceThb: 1500,
  },
  {
    id: "thongsala-night-market",
    name: "שוק הלילה פאנטיפ",
    nameEn: "Pantip Night Market, Thong Sala",
    region: "phangan",
    category: "market",
    lat: 9.709,
    lng: 99.988,
    hook: "שוק האוכל של ת'ונג סאלה, כל ערב מ-16:00.",
    tip: "פירות, שייקים ומזכרות. האוכל המבושל לא כשר — לבוא לפירות ולאווירה.",
    priceThb: 0,
  },
  {
    id: "sri-thanu",
    name: "סרי ת'אנו",
    nameEn: "Sri Thanu",
    region: "phangan",
    category: "nature",
    lat: 9.742,
    lng: 99.964,
    hook: "בירת היוגה והוולנס של האי, בצד המערבי.",
    tip: "שיעורי יוגה חד-פעמיים ~300-400 באט בלי הרשמה מראש. גם אם זה לא הקטע שלכם — האזור עצמו יפה.",
  },

  // ═══════════ בנגקוק — תוספות ═══════════
  {
    id: "rambuttri",
    name: "רחוב רמבוטרי",
    nameEn: "Soi Rambuttri",
    region: "bangkok",
    category: "market",
    lat: 13.7605,
    lng: 100.4962,
    hook: 'האח השפוי של קאו סאן — עצים, ברים שקטים, ובית חב"ד באותו רחוב.',
    tip: "פה כדאי לישון. שתי דקות מקאו סאן כשרוצים רעש, ושקט כשלא.",
  },
  {
    id: "wat-traimit",
    name: "ואט טריימיט — הבודהה מזהב",
    nameEn: "Wat Traimit (Golden Buddha)",
    region: "bangkok",
    category: "temple",
    lat: 13.7378,
    lng: 100.5138,
    hook: "5.5 טון של זהב מלא. התגלה במקרה ב-1955 מתחת לשכבת טיח.",
    tip: "בכניסה לצ'יינה טאון — לשלב עם יאווארט. 100 באט, חצי שעה.",
    priceThb: 100,
  },
  {
    id: "wat-benchamabophit",
    name: "מקדש השיש",
    nameEn: "Wat Benchamabophit (Marble Temple)",
    region: "bangkok",
    category: "temple",
    lat: 13.7663,
    lng: 100.5147,
    hook: "שיש קררה איטלקי בצורת מקדש תאילנדי. זה שעל מטבע ה-5 באט.",
    tip: "הכי יפה ב-6:30 בבוקר כשהנזירים מקבלים נדבות. שקט, בלי קבוצות.",
    priceThb: 100,
  },
  {
    id: "wat-suthat",
    name: "ואט סותאט והנדנדה הענקית",
    nameEn: "Wat Suthat & Giant Swing",
    region: "bangkok",
    category: "temple",
    lat: 13.7513,
    lng: 100.5013,
    hook: "אולם התפילה הכי מרשים בעיר, וכמעט בלי תיירים.",
    tip: "10 דקות הליכה מהר הזהב. 100 באט, וזה מקדש שבאמת שווה את העצירה.",
    priceThb: 100,
  },
  {
    id: "wat-paknam",
    name: "ואט פאקנאם — הסטופה הירוקה",
    nameEn: "Wat Paknam",
    region: "bangkok",
    category: "temple",
    lat: 13.7103,
    lng: 100.4671,
    hook: "כיפת זכוכית ירוקה בקומה החמישית, ובחוץ בודהה ענק בן 69 מטר.",
    tip: "חינם. קצת מחוץ למרכז — גראב או MRT לבנג פאי. הכי מצולם בבנגקוק כרגע.",
    priceThb: 0,
  },
  {
    id: "talat-noi",
    name: "טלאט נוי",
    nameEn: "Talat Noi",
    region: "bangkok",
    category: "market",
    lat: 13.7372,
    lng: 100.5128,
    hook: "שכונת מוסכים סינית ישנה שהפכה לגלריית גרפיטי על הנהר.",
    tip: "לשלב עם צ'יינה טאון. הכי טוב באור אחר הצהריים. חינם.",
    priceThb: 0,
  },
  {
    id: "jim-thompson",
    name: "בית ג'ים תומפסון",
    nameEn: "Jim Thompson House",
    region: "bangkok",
    category: "market",
    lat: 13.7492,
    lng: 100.5283,
    hook: "בית עץ תאילנדי מסורתי של איל המשי האמריקאי שנעלם בג'ונגל ב-1967.",
    tip: "נווה מדבר ירוק באמצע העיר, דקות מסיאם. סיור מודרך כלול במחיר.",
    priceThb: 200,
    duration: "שעה",
  },
  {
    id: "erawan-shrine",
    name: "מקדש אראוואן",
    nameEn: "Erawan Shrine",
    region: "bangkok",
    category: "temple",
    lat: 13.7443,
    lng: 100.5403,
    hook: "מקדש הינדי קטן בין הקניונים, עם רקדניות מסורתיות ומיליון קטורת.",
    tip: "חינם, פתוח כל היום, ובדיוק בצומת של ראצ'פראסונג. עצירה של 15 דקות.",
    priceThb: 0,
  },
  {
    id: "siam-mbk",
    name: "סיאם ו-MBK",
    nameEn: "Siam Square & MBK Center",
    region: "bangkok",
    category: "market",
    lat: 13.7447,
    lng: 100.53,
    hook: "לב הקניות של בנגקוק — MBK לזול ומיקוח, פאראגון ליוקרה.",
    tip: "ב-MBK מתמקחים על הכל: מזוודות, אלקטרוניקה, מזכרות. מתחילים מחצי מהמחיר.",
  },
  {
    id: "terminal21",
    name: "טרמינל 21",
    nameEn: "Terminal 21 Asok",
    region: "bangkok",
    category: "market",
    lat: 13.7376,
    lng: 100.5604,
    hook: "קניון שכל קומה בו היא עיר אחרת — טוקיו, לונדון, איסטנבול.",
    tip: "השירותים שם הם אטרקציה בפני עצמה. מזגן חינם וממוזג ליום גשום.",
  },
  {
    id: "iconsiam",
    name: "אייקונסיאם",
    nameEn: "ICONSIAM",
    region: "bangkok",
    category: "market",
    lat: 13.7263,
    lng: 100.51,
    hook: "הקניון הכי מרשים באסיה, על הנהר, עם שוק צף בתוכו.",
    tip: "מעבורת חינם מרציף סאתון. מרפסת הנהר בשקיעה — חינם ומדהים.",
    priceThb: 0,
  },
  {
    id: "asiatique",
    name: "אסיאטיק",
    nameEn: "Asiatique The Riverfront",
    region: "bangkok",
    category: "market",
    lat: 13.7045,
    lng: 100.5029,
    hook: "מחסני נמל ישנים שהפכו לשוק לילה על הנהר, עם גלגל ענק.",
    tip: "מעבורת חינם מרציף סאתון מ-16:00. יותר מסודר ופחות אותנטי מהשווקים האחרים.",
    priceThb: 0,
  },
  {
    id: "lumphini",
    name: "פארק לומפיני",
    nameEn: "Lumphini Park",
    region: "bangkok",
    category: "nature",
    lat: 13.7307,
    lng: 100.5418,
    hook: "הריאה הירוקה של בנגקוק, עם לטאות ענק שמסתובבות חופשי.",
    tip: "בוקר מוקדם — טאי צ'י של המקומיים. הוורנים באמת גדולים ובאמת לא מסוכנים.",
    priceThb: 0,
  },
  {
    id: "bang-krachao",
    name: "באנג קראצ'או — הריאה הירוקה",
    nameEn: "Bang Krachao",
    region: "bangkok",
    category: "nature",
    lat: 13.689,
    lng: 100.556,
    hook: "ג'ונגל בתוך העיר — שבילי אופניים מוגבהים בין עצים, בקצה הנהר.",
    tip: "מעבורת קטנה מרציף קלונג טוי, ואז אופניים ב-100 באט. חצי יום, ואפס תיירים.",
    priceThb: 150,
    duration: "חצי יום",
  },
  {
    id: "sky-bar",
    name: "בר גג בסילום",
    nameEn: "Rooftop Bars, Silom",
    region: "bangkok",
    category: "party",
    lat: 13.7218,
    lng: 100.5168,
    hook: "בנגקוק מלמעלה. לבואה/סקיי בר, ורטיגו, ועוד עשרות.",
    tip: "קוד לבוש: בלי כפכפים ובלי גופייה, גם לגברים. משקה אחד עולה 500+ באט — באים לנוף, לא לשתות.",
    priceThb: 600,
  },
  {
    id: "maeklong-damnoen",
    name: "שוק הרכבת ושוק צף",
    nameEn: "Maeklong Railway & Damnoen Saduak",
    region: "bangkok",
    category: "market",
    lat: 13.409,
    lng: 99.9987,
    hook: "שוק שמתקפל כשהרכבת עוברת בתוכו, ושוק צף בסירות. יום שלם מחוץ לעיר.",
    details:
      "שני האתרים באותו כיוון, שעה וחצי מבנגקוק, ולכן מוכרים אותם כסיור אחד.",
    tip: "לצאת ב-6:00 כדי להקדים את האוטובוסים. השוק הצף מתויר מאוד — הרכבת היא החלק המרשים.",
    priceThb: 1200,
    duration: "יום שלם",
  },

  // ═══════════ לאכול כשר בפוקט ═══════════
  {
    id: "gafniko-phuket",
    name: "ג׳פניקו (Japaniko)",
    nameEn: "Japaniko",
    region: "phuket",
    category: "kosher",
    lat: 7.8918,
    lng: 98.2972,
    approx: true,
    hours: 'א\'-ה\' 12:00-24:00 · שישי 12:00-16:00 · מוצ"ש 20:00-24:00',
    hook: "אסייתי וסושי כשר למהדרין על הפאטונג — האוכל התאילנדי שסוף סוף מותר לכם.",
    details:
      "אינסטגרם @japaniko_phuket. פתוח עד חצות, כולל מוצאי שבת — נדיר בתאילנד.",
    tip: "שימו לב לשישי — נסגר ב-16:00, ובמוצ\"ש נפתח רק ב-20:00.",
    priceThb: 500,
  },
  {
    id: "shipudei-babi",
    name: "שיפודי באבי",
    nameEn: "Babi's Skewers",
    region: "phuket",
    category: "kosher",
    lat: 7.8905,
    lng: 98.298,
    approx: true,
    hook: "גריל ושיפודים כשרים — בשרי, ישראלי, מנות גדולות.",
    tip: "המיקום כאן משוער — לאמת בגוגל מפות ולוודא שעות. אם זה בכלל לא בפוקט, תגיד לי ואני מעביר לאי הנכון.",
    priceThb: 400,
  },
  {
    id: "chabad-phuket-meals",
    name: "סעודות שבת וחג — פאטונג",
    nameEn: "Shabbat & Chag meals, Chabad Phuket",
    region: "phuket",
    category: "kosher",
    lat: 7.8911,
    lng: 98.2999,
    approx: true,
    hook: "הארוחות החמות היחידות שיהיו לכם בשבת 26.9 ובשבת 10.10.",
    details:
      "סעודת ליל שבת/חג וסעודת יום. בשר, סלטים, חלה ויין — סטנדרט חב\"ד. בסוכות הכל מוגש בסוכה.",
    tip: "להירשם ימים מראש, לא ביום שישי. תרומה מקובלת ~300-500 באט לסעודה, במזומן. אם אתם חבורה — לציין כמה אתם כשנרשמים.",
    priceThb: 400,
  },
  {
    id: "sukkah-phuket",
    name: "הסוכה בבית חב\"ד פאטונג",
    nameEn: "The Sukkah, Chabad Phuket",
    region: "phuket",
    category: "kosher",
    lat: 7.8909,
    lng: 98.2996,
    approx: true,
    hook: "25.9 עד 1.10 — לאכול בסוכה בחצר, גם באמצע השבוע.",
    details:
      "בחול המועד (27.9-1.10) הסוכה פתוחה גם בימי חול, ואפשר לאכול בה כל ארוחה.",
    tip: "גם אם אתם לא נשארים לסעודה — לקפוץ לקידוש ולברך על הסוכה. זו בערך הפעם היחידה בחיים שתעשו את זה מול חוף טרופי.",
  },
  {
    id: "banzaan-market",
    name: "שוק באנזאן — פאטונג",
    nameEn: "Banzaan Fresh Market",
    region: "phuket",
    category: "kosher",
    lat: 7.8925,
    lng: 98.2985,
    hook: "שוק הפירות והירקות המסודר של פאטונג — הבסיס לכל אוכל עצמאי.",
    details:
      "פירות שלמים, ירקות, ביצים. הכל בקומה הראשונה; הקומה השנייה היא מטבחים ולא רלוונטית לכם.",
    tip: "פירות שלמים שאתם קולפים בעצמכם זה הפתרון הכי פשוט וזול בטיול. מנגו, אננס, פסיפלורה, מנגוסטין.",
    priceThb: 150,
  },
  {
    id: "chalong-market",
    name: "השוק הטרי בצ'אלונג",
    nameEn: "Chalong Fresh Market",
    region: "phuket",
    category: "kosher",
    lat: 7.847,
    lng: 98.338,
    approx: true,
    hook: "שוק מקומי אמיתי בדרום האי — פירות בחצי מחיר מפאטונג.",
    tip: "פתוח בבוקר. בדרך מקארון לוואט צ'אלונג — לעצור ולמלא את התיק.",
    priceThb: 100,
  },
  {
    id: "makro-phuket",
    name: "מאקרו / לוטוס — קניות לפני חג",
    nameEn: "Makro & Lotus's, Phuket",
    region: "phuket",
    category: "kosher",
    lat: 7.888,
    lng: 98.366,
    approx: true,
    hook: "סופר סיטונאי — פה קונים בכמויות לפני שבת ולפני החגים.",
    details:
      "מים במארזים, פירות, ירקות, קטניות בקופסה, ומוצרים מיובאים עם הכשר.",
    tip: "הקנייה הקריטית: ערב חמישי 24.9 לפני סוכות. אחרי שהחג נכנס אין קניות ואין כספומט.",
  },
  {
    id: "phuket-street-safe",
    name: "קוקוס ופירות ברחוב",
    nameEn: "Coconuts & street fruit, Phuket",
    region: "phuket",
    category: "kosher",
    lat: 7.844,
    lng: 98.298,
    approx: true,
    hook: "הדבר היחיד שאפשר לקנות ברחוב בלי לחשוב פעמיים.",
    details:
      "קוקוס שלם שנפתח מולכם, ופירות שלמים בקליפה. דוכנים כאלה יש בכל חוף ובכל רחוב ראשי.",
    tip: "שייקים זה כבר סיפור אחר — הבלנדר טוחן הכל, והקרח ממקור לא ידוע. אם זה חשוב לכם, תשאלו את הרב בחב\"ד מה הוא אומר על זה.",
    priceThb: 60,
  },

  // ═══════════ לאכול כשר בקוסמוי ═══════════
  {
    id: "chabad-samui-meals",
    name: "סעודות החג — צ'אוונג",
    nameEn: "Chag meals, Chabad Koh Samui",
    region: "samui",
    category: "kosher",
    lat: 9.533,
    lng: 100.062,
    approx: true,
    hook: "חמש סעודות רצופות ב-2-4.10. זה כל האוכל שלכם בשלושת הימים האלה.",
    details:
      "שמיני עצרת, שבת ושמחת תורה — ליל חג, יום, ליל שבת, יום שבת, וליל שמחת תורה. הקפות ביום ראשון.",
    tip: "להירשם שבועות מראש. זה החג הכי עמוס בשנה בבתי חב\"ד באיים, ואם לא נרשמתם — אין לכם איפה לאכול.",
    priceThb: 400,
  },
  {
    id: "sukkah-samui",
    name: "הסוכה בבית חב\"ד סמוי",
    nameEn: "The Sukkah, Chabad Koh Samui",
    region: "samui",
    category: "kosher",
    lat: 9.533,
    lng: 100.062,
    approx: true,
    hook: "30.9 ו-1.10 — שני ימי חול המועד שאתם בסמוי.",
    tip: "מגיעים ב-30.9 בערב? זו ארוחה ראשונה טובה על האי, ואפשרות לסגור מולם את הרישום לחג.",
  },
  {
    id: "samui-fresh-markets",
    name: "שווקי הפירות של סמוי",
    nameEn: "Samui Fresh Markets",
    region: "samui",
    category: "kosher",
    lat: 9.539,
    lng: 99.9375,
    hook: "נאת'ון בבוקר, לאמאי כל יום, ומאנם בימי חמישי.",
    details:
      "השוק בנאת'ון הוא הזול והאמיתי באי. פירות, ירקות, ביצים, אגוזים.",
    tip: "לקנות פירות ל-2-3 ימים קדימה לפני הבלוק של החג. דוריאן — אם אתם מנסים, לא בחדר. הריח נשאר שבוע.",
    priceThb: 120,
  },
  {
    id: "makro-samui",
    name: "מאקרו / ביג סי — קניות לחג",
    nameEn: "Makro & Big C, Samui",
    region: "samui",
    category: "kosher",
    lat: 9.545,
    lng: 100.047,
    approx: true,
    hook: "הקנייה הגדולה לפני שלושת ימי החג ב-2-4.10.",
    tip: "לעשות אותה ביום חמישי 1.10 אחרי אנג ת'ונג. מים, פירות, קטניות בקופסה, קרקרים, וכל מה שנושא הכשר.",
  },
  {
    id: "samui-street-safe",
    name: "קוקוס ופירות ברחוב — סמוי",
    nameEn: "Coconuts & street fruit, Samui",
    region: "samui",
    category: "kosher",
    lat: 9.534,
    lng: 100.061,
    approx: true,
    hook: "דוכני קוקוס ופירות חתוכים לאורך צ'אוונג ולאמאי.",
    tip: "קוקוס שנפתח מולכם — הכי פשוט. פירות חתוכים מראש בשקית: הסכין שלהם, אז עדיף שלם.",
    priceThb: 60,
  },
  {
    id: "self-catering-samui",
    name: "לבשל בחדר",
    nameEn: "Self-catering",
    region: "samui",
    category: "kosher",
    lat: 9.531,
    lng: 100.06,
    approx: true,
    hook: "בונגלו עם מטבחון פותר לכם חצי מהבעיה בשני האיים.",
    details:
      "ביצים, אורז, ירקות, פסטה וטונה — הכל זמין בסופר, והכלים חדשים מהחנות.",
    tip: "לקנות סיר, מחבת וסכין זולים במאקרו (~400 באט לסט) ולהשאיר אותם בחב\"ד בסוף. דגים: רק עם סנפיר וקשקשת, שלמים, ולנקות בעצמכם. בכל שאלה — הרב בחב\"ד עונה, זה בדיוק התפקיד שלו.",
    priceThb: 400,
  },

  // ═══════════ מסעדות כשרות נוספות ═══════════
  {
    id: "four-spices-samui",
    name: "4 Spices",
    nameEn: "4 Spices",
    region: "samui",
    category: "kosher",
    lat: 9.5352,
    lng: 100.0628,
    approx: true,
    hook: "מסעדת שף אסייתית — הכי מומלצת מבין הכשרות בקוסמוי.",
    details: "אינסטגרם @4_spices_samui. חוזרת בהמלצות משני מקורות שונים.",
    tip: "אם יש ערב אחד לבזבז עליו בקוסמוי — זה הוא. להזמין מקום מראש.",
    priceThb: 600,
  },
  {
    id: "tom-yam-samui",
    name: "תום ים",
    nameEn: "Tom Yam",
    region: "samui",
    category: "kosher",
    lat: 9.5348,
    lng: 100.0632,
    approx: true,
    hook: "אסייתית כשרה בצ׳אוונג עם תפריט רחב של מנות מקומיות.",
    tip: "הדרך לאכול תאילנדי אמיתי בלי לוותר על כשרות.",
    priceThb: 450,
  },
  {
    id: "zohara-samui",
    name: "זוהרה",
    nameEn: "Zohara",
    region: "samui",
    category: "kosher",
    lat: 9.5332,
    lng: 100.0608,
    approx: true,
    hook: 'מסעדת בית בצ׳אוונג, אוכל מנחם ותפריט גדול. מוגדרת כ"אסור לפספס".',
    tip: "כשנמאס מאסייתי ורוצים משהו שמרגיש כמו בית.",
    priceThb: 400,
  },
  {
    id: "arancini-samui",
    name: "ארנצ׳יני",
    nameEn: "Arancini",
    region: "samui",
    category: "kosher",
    lat: 9.5336,
    lng: 100.0626,
    approx: true,
    hook: "חלבית בצ׳אוונג עם תפריט מגוון — והכתובת לארוחת בוקר באזור.",
    tip: "ארוחת בוקר לפני יום השייט לאנג ת׳ונג.",
    priceThb: 300,
  },
  {
    id: "banana-roti-kosher",
    name: "בננה רוטי כשר",
    nameEn: "Kosher Banana Roti",
    region: "samui",
    category: "kosher",
    lat: 9.5325,
    lng: 100.0605,
    approx: true,
    hook: "הרוטי הרחובי הקלאסי בגרסה כשרה.",
    details:
      "המיקום לא פורסם בפומבי — נשלח בהודעה פרטית. פורסם דרך @shimrit_travel.",
    tip: "המיקום כאן הוא מציין מקום בלבד — לפנות למפרסמת באינסטגרם כדי לקבל את הכתובת.",
    priceThb: 80,
  },
  {
    id: "jungle-club",
    name: "Jungle Club",
    nameEn: "Jungle Club Samui",
    region: "samui",
    category: "viewpoint",
    lat: 9.524,
    lng: 100.029,
    approx: true,
    hook: "תצפית בהרים מעל מפרץ צ׳אוונג. אחר צהריים מאוחר צובע הכל בזהב.",
    details: "האוכל שם לא כשר — באים בשביל הנוף והישיבה.",
    tip: "הדרך למעלה תלולה ומפחידה — לא לעלות בקטנוע חלש עם שניים. מונית או ג׳יפ.",
    priceThb: 0,
  },
  {
    id: "the-best-samui",
    name: "The Best Samui",
    nameEn: "The Best Samui Viewpoint",
    region: "samui",
    category: "viewpoint",
    lat: 9.51,
    lng: 100.04,
    approx: true,
    hook: "תצפית חדשה ומושקעת שישראלים עוד לא ממש מכירים.",
    tip: "אלטרנטיבה לג׳אנגל קלאב כשרוצים פחות עומס.",
  },
  {
    id: "lipa-noi",
    name: "ליפה נוי",
    nameEn: "Lipa Noi Beach",
    region: "samui",
    category: "beach",
    lat: 9.464,
    lng: 99.942,
    hook: "חוף רדוד וארוך בצד המערבי — שקיעות ישר לים.",
    tip: "הרבה יותר שקט מצ׳אוונג. שווה נסיעה לשקיעה אחת.",
  },
  {
    id: "ocean-vibes-phangan",
    name: "Ocean Vibes — שקיעה",
    nameEn: "Ocean Vibes",
    region: "phangan",
    category: "viewpoint",
    lat: 9.748,
    lng: 99.959,
    approx: true,
    hook: "השקיעה הכי יפה בקופנגן לפי מי שגר שם.",
    tip: "להגיע 45 דקות לפני. האוכל לא כשר — באים לשקיעה.",
  },
  {
    id: "phangan-wellness",
    name: "יוגה, מואי תאי וספא",
    nameEn: "Yoga House · MAA · Xantiva",
    region: "phangan",
    category: "nature",
    lat: 9.744,
    lng: 99.966,
    approx: true,
    hook: "Yoga House ליוגה, MAA למואי תאי, ו-Xantiva לספא עם אמבטיית קרח.",
    tip: "הכל באזור סרי ת׳אנו. שיעור בודד בלי הרשמה מראש ~300-400 באט.",
    priceThb: 400,
  },
  {
    id: "andamanda",
    name: "Andamanda — פארק מים",
    nameEn: "Andamanda Phuket",
    region: "phuket",
    category: "fun",
    lat: 7.913,
    lng: 98.341,
    approx: true,
    hook: "פארק המים הגדול של פוקט, בעיצוב תאילנדי.",
    tip: "כרטיסים אונליין זולים משמעותית מהקופה. יום שלם, ולהביא קרם הגנה.",
    priceThb: 1500,
    duration: "יום",
  },
  {
    id: "dinner-in-the-sky",
    name: "Dinner in the Sky",
    nameEn: "Dinner in the Sky Phuket",
    region: "phuket",
    category: "fun",
    lat: 7.833,
    lng: 98.301,
    approx: true,
    hook: "שולחן שמורם על מנוף מעל האי. חוויה, לא ארוחה.",
    tip: "לא כשר — אפשר לבדוק מולם אם אפשר לעלות לשתייה סגורה בלבד. יקר, ובכל זאת חוזר בהמלצות.",
    priceThb: 4000,
  },
  {
    id: "mai-khao",
    name: "מאי קאו ביץ׳",
    nameEn: "Mai Khao Beach",
    region: "phuket",
    category: "beach",
    lat: 8.13,
    lng: 98.296,
    hook: "החוף הארוך והשקט בצפון האי, ליד שדה התעופה.",
    tip: "11 ק״מ של חול כמעט ריק, וגם המקום שרואים ממנו מטוסים נוחתים נמוך.",
  },
  {
    id: "fantasea",
    name: "Phuket FantaSea",
    nameEn: "Phuket FantaSea",
    region: "phuket",
    category: "fun",
    lat: 7.954,
    lng: 98.279,
    approx: true,
    hook: "מופע ראווה תאילנדי ענק בקמאלה — תרבות, אורות ופירוטכניקה.",
    tip: "לקנות רק את המופע בלי ארוחת הערב — היא לא כשרה ממילא.",
    priceThb: 1800,
    duration: "ערב",
  },
  {
    id: "emsphere",
    name: "Emsphere",
    nameEn: "Emsphere Bangkok",
    region: "bangkok",
    category: "market",
    lat: 13.73,
    lng: 100.569,
    hook: "הקניון החדש של סוכומוויט, עם קומת אוכל שלמה.",
    tip: "BTS פרום פונג. ממוזג ופתוח עד מאוחר — טוב לערב גשום.",
  },
  {
    id: "chocolate-ville",
    name: "Chocolate Ville",
    nameEn: "Chocolate Ville",
    region: "bangkok",
    category: "fun",
    lat: 13.828,
    lng: 100.669,
    approx: true,
    hook: 'כפר אירופאי מואר של מסעדות — "הדיסנילנד החינמי" של בנגקוק.',
    details: "בבאנג קאפי, כ-30 דקות מהמרכז. כניסה 150 באט שחוזרים כקרדיט.",
    tip: "האוכל לא כשר, אבל הכניסה חוזרת כקרדיט לשתייה סגורה. באים לצילומים בשקיעה.",
    priceThb: 150,
  },
  {
    id: "lomlom-massage",
    name: "Lomlom — מסאז׳",
    nameEn: "Lomlom Massage",
    region: "bangkok",
    category: "nature",
    lat: 13.744,
    lng: 100.534,
    approx: true,
    hook: "המסאז׳ הכי מקצועי בעיר לפי האוסף.",
    tip: "להזמין מראש. מסאז׳ תאילנדי טוב בבנגקוק הוא 300-600 באט לשעה.",
    priceThb: 500,
  },
];




export const PLACE_BY_ID = Object.fromEntries(
  PLACES.map((p) => [p.id, p]),
) as Record<string, Place>;
