import type { Place } from "./types";

/**
 * הקואורדינטות נבדקו מול מפות פתוחות, אבל מקומות בתאילנד זזים —
 * כל מקום שמסומן approx צריך אימות בגוגל מפות לפני שנוסעים אליו.
 * מסעדות ובתי חב"ד: תמיד להתקשר/לבדוק שעות לפני, במיוחד בחגים.
 */
export const PLACES: Place[] = [
  // ─────────────────────────── בנגקוק ───────────────────────────
  {
    id: "chabad-bangkok-khaosan",
    name: 'בית חב"ד בנגקוק — קאו סאן',
    nameEn: "Chabad House Bangkok (Khaosan)",
    region: "bangkok",
    category: "chabad",
    lat: 13.7601,
    lng: 100.4966,
    approx: true,
    hook: 'המרכז הישראלי של בנגקוק — רמבוטרי רואד, דקה מקאו סאן.',
    details:
      'בית הכנסת, מסעדת "בית אלישבע" הכשרה, ארוחות שבת וחג, ומידע לישראלים. בסוכות יש סוכה גדולה בחצר.',
    tip: 'להירשם לסעודות שבת/חג מראש דרך האתר או בטלפון — בסוכות זה מתמלא. תרומה מקובלת ~300-500 באט לסעודה.',
    url: "https://www.chabadthailand.com/",
  },
  {
    id: "chabad-bangkok-sukhumvit",
    name: 'בית חב"ד סוכומוויט',
    nameEn: "Chabad Sukhumvit (Ohr Menachem)",
    region: "bangkok",
    category: "chabad",
    lat: 13.7318,
    lng: 100.5651,
    approx: true,
    hook: "הסניף בצד המודרני של העיר, קרוב למלונות ולקניונים.",
    details:
      "בית כנסת ומטבח כשר. נוח אם אתם ישנים באזור סוכומוויט/אסוק ולא בקאו סאן.",
    tip: "מ-BTS אסוק זו הליכה קצרה. בשבת אין BTS-קארד לשלם בו — לסדר מזומן מראש או ללכת ברגל.",
  },
  {
    id: "kosher-bet-elisheva",
    name: "מסעדת בית אלישבע (כשר)",
    nameEn: "Bet Elisheva Kosher Restaurant",
    region: "bangkok",
    category: "kosher",
    lat: 13.7601,
    lng: 100.4966,
    approx: true,
    hook: 'המסעדה הכשרה של חב"ד קאו סאן — בשרי, ישראלי, מנות גדולות.',
    details:
      'תחת השגחת בית חב"ד תאילנד. שניצלים, חומוס, פלאפל וגם אוכל תאילנדי כשר.',
    tip: "אחרי טיסה ארוכה זה המקום הראשון שכדאי לכם — וגם המקום להזמין בו אוכל לדרך לאיים.",
    priceThb: 350,
  },
  {
    id: "grand-palace",
    name: "הארמון המלכותי + ואט פרה קאו",
    nameEn: "Grand Palace & Wat Phra Kaew",
    region: "bangkok",
    category: "temple",
    lat: 13.75,
    lng: 100.4913,
    hook: "האתר מספר 1 בתאילנד — הבודהה הירוק וזהב עד האופק.",
    tip: "קוד לבוש נוקשה: כתפיים וברכיים מכוסות, גם לגברים. להגיע ב-8:30 בפתיחה, אחרת חום + תורים. מתעלמים מכל מי שאומר לכם ברחוב 'סגור היום' — זו הונאה קלאסית.",
    priceThb: 500,
    duration: "2-3 שעות",
  },
  {
    id: "wat-pho",
    name: "ואט פו — הבודהה השוכב",
    nameEn: "Wat Pho",
    region: "bangkok",
    category: "temple",
    lat: 13.7465,
    lng: 100.4927,
    hook: "46 מטר של בודהה זהב שוכב, ובית הספר הוותיק לעיסוי תאילנדי.",
    tip: "10 דקות הליכה מהארמון — לשלב באותו בוקר. עיסוי תאילנדי אותנטי בתוך המתחם ~480 באט לשעה.",
    priceThb: 300,
    duration: "שעה",
  },
  {
    id: "wat-arun",
    name: "ואט ארון — מקדש השחר",
    nameEn: "Wat Arun",
    region: "bangkok",
    category: "temple",
    lat: 13.7437,
    lng: 100.4889,
    hook: "הצריח שמצופה בשברי חרסינה, על גדת הצ'או פראיה.",
    tip: "הכי יפה בשקיעה מהגדה הנגדית. מעבורת מוואט פו ב-5 באט.",
    priceThb: 200,
    duration: "שעה",
  },
  {
    id: "khaosan",
    name: "רחוב קאו סאן",
    nameEn: "Khaosan Road",
    region: "bangkok",
    category: "party",
    lat: 13.759,
    lng: 100.4977,
    hook: "בירת התרמילאים בעולם. רועש, זול, קיטשי — וחובה פעם אחת.",
    tip: 'רמבוטרי הסמוך יותר נעים ופחות מטורף. הקומבינה: לישון ברמבוטרי, לצאת לקאו סאן. גם בית חב"ד ממש שם.',
    priceThb: 0,
  },
  {
    id: "chatuchak",
    name: "שוק צ'אטוצ'ק",
    nameEn: "Chatuchak Weekend Market",
    region: "bangkok",
    category: "market",
    lat: 13.7999,
    lng: 100.5502,
    hook: "15,000 דוכנים. השוק הגדול בעולם, ורק בסופ\"ש.",
    details: "פתוח שבת-ראשון בעיקר (9:00-18:00), חלקים גם בשישי בערב.",
    tip: "שימו לב — פתוח בעיקר בשבת. בטיול הזה השבתות תפוסות, אז אם רוצים שוק, ג'וד פיירס בערב הוא התחליף.",
    priceThb: 0,
    duration: "3-4 שעות",
  },
  {
    id: "jodd-fairs",
    name: "שוק לילה ג'וד פיירס",
    nameEn: "Jodd Fairs Night Market",
    region: "bangkok",
    category: "market",
    lat: 13.7566,
    lng: 100.5657,
    approx: true,
    hook: "שוק הלילה הכי חי בבנגקוק כרגע — אוכל, אורות, בירה זולה.",
    tip: 'האוכל שם לא כשר — לאכול לפני בחב"ד ולבוא בשביל האווירה והקניות. MRT לתחנת Phra Ram 9.',
    priceThb: 0,
    duration: "2-3 שעות",
  },
  {
    id: "yaowarat",
    name: "צ'יינה טאון — יאווארט",
    nameEn: "Yaowarat (Chinatown)",
    region: "bangkok",
    category: "market",
    lat: 13.7398,
    lng: 100.51,
    hook: "רחוב אחד של ניאון, קיטור ואופנועים. הכי פוטוגני בלילה.",
    tip: "הכי טוב מ-19:00. ללכת ברגל מהמעגן, לא לנסוע — התנועה שם רצח.",
    priceThb: 0,
  },
  {
    id: "golden-mount",
    name: "הר הזהב (ואט סאקט)",
    nameEn: "Wat Saket / Golden Mount",
    region: "bangkok",
    category: "viewpoint",
    lat: 13.7539,
    lng: 100.5068,
    hook: "300 מדרגות ל-360 מעלות מעל העיר העתיקה.",
    tip: "לעלות שעה לפני שקיעה. 15 דקות הליכה מקאו סאן.",
    priceThb: 100,
    duration: "שעה",
  },
  {
    id: "muay-thai",
    name: "אצטדיון מואי תאי ראג'אדמנרן",
    nameEn: "Rajadamnern Stadium",
    region: "bangkok",
    category: "party",
    lat: 13.7583,
    lng: 100.5063,
    hook: "האצטדיון הוותיק בתאילנד. קרבות אמיתיים, קהל משוגע.",
    tip: "לקנות כרטיסים אונליין (זול יותר מהקופה). היציע העליון הכי כיף — שם ההימורים והצעקות.",
    priceThb: 1200,
    duration: "3 שעות",
  },
  {
    id: "chao-phraya-boat",
    name: "סירת אקספרס בצ'או פראיה",
    nameEn: "Chao Phraya Express Boat",
    region: "bangkok",
    category: "transport",
    lat: 13.742,
    lng: 100.51,
    hook: "התחבורה הכי יפה בעיר — 16 באט וזה גם סיור נהר.",
    tip: "הדגל הכתום הוא הקו השימושי. מרציף Phra Athit (קאו סאן) עד ואט ארון/ואט פו.",
    priceThb: 16,
  },
  {
    id: "ayutthaya",
    name: "איות'איה — הבירה העתיקה",
    nameEn: "Ayutthaya",
    region: "bangkok",
    category: "temple",
    lat: 14.356,
    lng: 100.568,
    hook: "חורבות מקדשים מהמאה ה-14 וראש הבודהה בתוך שורשי העץ.",
    tip: "יום שלם. רכבת מתחנת קרונג ת'פ אפיוואט ~20 באט, ואז אופניים/טוק טוק בין האתרים. אפשרי רק אם יש לכם יום פנוי בבנגקוק.",
    priceThb: 400,
    duration: "יום שלם",
  },

  // ─────────────────────────── קופנגן ───────────────────────────
  {
    id: "chabad-phangan",
    name: 'בית חב"ד קופנגן',
    nameEn: "Chabad Koh Phangan",
    region: "phangan",
    category: "chabad",
    lat: 9.705,
    lng: 99.995,
    approx: true,
    hook: "בית כנסת + מטבח כשר באזור ת'ונג סאלה / באן טאי.",
    details:
      "פועל בעונה, סעודות שבת וחג. בתקופת פול מון זה מתמלא בישראלים — להירשם מראש.",
    tip: 'המיקום המדויק משתנה בין עונות — לוודא בטלפון או בעמוד של חב"ד תאילנד לפני שמזמינים מונית.',
    url: "https://www.chabadthailand.com/",
  },
  {
    id: "kosher-phangan",
    name: 'מטבח כשר — חב"ד קופנגן',
    nameEn: "Kosher Kitchen Koh Phangan",
    region: "phangan",
    category: "kosher",
    lat: 9.705,
    lng: 99.995,
    approx: true,
    hook: "האופציה הכשרה היחידה על האי.",
    tip: "שעות פתיחה מוגבלות ולא כל יום. בימים שאין — לקנות טונה/קטניות/פירות בסופר בת'ונג סאלה.",
    priceThb: 300,
  },
  {
    id: "full-moon-party",
    name: "פול מון פארטי — האד רין",
    nameEn: "Full Moon Party, Haad Rin",
    region: "phangan",
    category: "party",
    lat: 9.674,
    lng: 100.068,
    hook: "30,000 איש על חוף אחד. הירח המלא בטיול שלכם: 26.9.",
    details:
      "מתחיל בערך ב-22:00 ונמשך עד הזריחה. כניסה ~200 באט. הירח המלא נופל במוצאי שבת/חג של סוכות — כלומר אפשר לעשות את שניהם.",
    tip: "אף פעם לא לוקחים ארנק. מזומן מוגבל בכיס, בלי טלפון יקר, נעליים סגורות (זכוכית שבורה בחול), ונקודת מפגש קבועה עם החברים כי הקליטה מתה. חבל האש — לא. באמת לא.",
    priceThb: 200,
  },
  {
    id: "haad-rin",
    name: "האד רין",
    nameEn: "Haad Rin Beach",
    region: "phangan",
    category: "beach",
    lat: 9.6785,
    lng: 100.067,
    hook: "חוף המסיבה עצמו — ביום זה חוף נורמלי ויפה.",
    tip: "לישון שם רק בלילה של הפול מון. שאר הזמן זה יקר ורועש בלי סיבה.",
  },
  {
    id: "bottle-beach",
    name: "בוטל ביץ' (האד קואט)",
    nameEn: "Bottle Beach (Haad Khuat)",
    region: "phangan",
    category: "beach",
    lat: 9.796,
    lng: 100.025,
    hook: "החוף הכי יפה באי, ומגיעים אליו רק בסירה או בהליכת ג'ונגל.",
    tip: "לונגטייל מצ'אלוקלום ~150-200 באט לכיוון. הסירה האחרונה חוזרת מוקדם (בערך 16:00) — לוודא שעה עם הנהג ולא להיתקע.",
    duration: "יום",
  },
  {
    id: "secret-beach",
    name: "סיקרט ביץ' (האד סון)",
    nameEn: "Secret Beach (Haad Son)",
    region: "phangan",
    category: "beach",
    lat: 9.753,
    lng: 99.956,
    hook: "מפרץ קטן בצד המערבי — שקיעה ישר לים.",
    tip: "הגישה בכביש תלול מאוד. אם אתם לא בטוחים על הקטנוע — מונית.",
  },
  {
    id: "zen-beach",
    name: "זן ביץ' — שקיעה",
    nameEn: "Zen Beach",
    region: "phangan",
    category: "beach",
    lat: 9.742,
    lng: 99.96,
    approx: true,
    hook: "שקיעה עם מתופפים, ג'אגלרים וכל הסצנה החופשית של האי.",
    tip: "להביא בירה ומחצלת ולהגיע 45 דקות לפני השקיעה.",
    priceThb: 0,
  },
  {
    id: "than-sadet",
    name: "מפל ת'אן סאדט",
    nameEn: "Than Sadet Waterfall",
    region: "phangan",
    category: "nature",
    lat: 9.753,
    lng: 100.074,
    hook: "מפל בג'ונגל עם בריכות טבעיות לקפוץ אליהן.",
    tip: "בסוף ספטמבר יש מים — זה סוף עונת הגשמים, הכי טוב שיהיה. הכביש לשם קשה לקטנוע חלש.",
    priceThb: 0,
  },
  {
    id: "khao-ra",
    name: "קאו רא — הפסגה של האי",
    nameEn: "Khao Ra Viewpoint",
    region: "phangan",
    category: "viewpoint",
    lat: 9.748,
    lng: 100.008,
    approx: true,
    hook: "627 מטר, תצפית על כל קופנגן וסמוי ברקע.",
    tip: "עלייה של שעה-שעה וחצי בג'ונגל. לצאת ב-6:30 בבוקר לפני החום, עם 2 ליטר מים לאדם.",
    duration: "3 שעות",
  },
  {
    id: "thong-sala",
    name: "ת'ונג סאלה — עיר הנמל",
    nameEn: "Thong Sala",
    region: "phangan",
    category: "market",
    lat: 9.71,
    lng: 99.99,
    hook: "הנמל, הבנקים, הסופר והשוק הלילי (פאנטיפ).",
    tip: "פה מגיעה ויוצאת המעבורת, ופה מצטיידים לפני שנתקעים בצד השני של האי.",
  },
  {
    id: "chaloklum",
    name: "צ'אלוקלום — כפר הדייגים",
    nameEn: "Chaloklum",
    region: "phangan",
    category: "beach",
    lat: 9.79,
    lng: 100.01,
    hook: "הצפון השקט, ומכאן יוצאות הסירות לבוטל ביץ'.",
  },

  // ─────────────────────────── קוסמוי ───────────────────────────
  {
    id: "chabad-samui",
    name: 'בית חב"ד קוסמוי',
    nameEn: "Chabad Koh Samui",
    region: "samui",
    category: "chabad",
    lat: 9.533,
    lng: 100.062,
    approx: true,
    hook: "בצ'אוונג, לב האזור התיירותי — בית כנסת ומסעדה כשרה.",
    details: "סעודות שבת, מניינים, ומידע עדכני על מעבורות וחגים באזור המפרץ.",
    tip: 'לבדוק שעות ומיקום מדויק באתר חב"ד תאילנד לפני שמגיעים.',
    url: "https://www.chabadthailand.com/",
  },
  {
    id: "kosher-samui",
    name: 'מסעדה כשרה — חב"ד צ\'אוונג',
    nameEn: "Kosher Restaurant Chaweng",
    region: "samui",
    category: "kosher",
    lat: 9.533,
    lng: 100.062,
    approx: true,
    hook: "בשרי כשר בלב צ'אוונג.",
    tip: "לתאם מראש, במיוחד בערבי חג. אפשר לקחת אוכל ארוז ליום שייט.",
    priceThb: 350,
  },
  {
    id: "big-buddha-samui",
    name: "הבודהה הגדול (ואט פרה יאי)",
    nameEn: "Big Buddha, Wat Phra Yai",
    region: "samui",
    category: "temple",
    lat: 9.5678,
    lng: 100.06,
    hook: "12 מטר של זהב מול הים, בצפון האי.",
    tip: "הרציף ליד הוא אחת האופציות למעבורת לקופנגן. חינם, 40 דקות.",
    priceThb: 0,
  },
  {
    id: "wat-plai-laem",
    name: "ואט פלאי לאם",
    nameEn: "Wat Plai Laem",
    region: "samui",
    category: "temple",
    lat: 9.5697,
    lng: 100.045,
    hook: "אלת הרחמים ב-18 זרועות, על אגם.",
    tip: "5 דקות מהבודהה הגדול — לשלב. חינם.",
    priceThb: 0,
  },
  {
    id: "ang-thong",
    name: "פארק ימי אנג ת'ונג",
    nameEn: "Ang Thong Marine Park",
    region: "samui",
    category: "boat",
    lat: 9.62,
    lng: 99.68,
    hook: "42 איי גיר, לגונה אמרלד וקיאקים. היום הכי יפה בכל המפרץ.",
    details:
      "יוצאים בבוקר מנאת'ון או מבופוט, חוזרים אחה\"צ. כולל שנרקול, קיאק ותצפית וו-טה-לאפ.",
    tip: "הזמינו סיור עם קיאקים ולא רק ספידבוט. הפארק נסגר לפעמים בים סוער — לבדוק ערב לפני. תביאו אוכל משלכם מהמסעדה הכשרה.",
    priceThb: 1800,
    duration: "יום שלם",
  },
  {
    id: "chaweng",
    name: "חוף צ'אוונג",
    nameEn: "Chaweng Beach",
    region: "samui",
    category: "beach",
    lat: 9.535,
    lng: 100.062,
    hook: "החוף הראשי — 6 ק\"מ של חול לבן, ברים ובתי מלון.",
    tip: 'הצפון של צ\'אוונג שקט יותר, הדרום זה החיים. בית חב"ד גם הוא כאן.',
  },
  {
    id: "lamai",
    name: "חוף לאמאי",
    nameEn: "Lamai Beach",
    region: "samui",
    category: "beach",
    lat: 9.46,
    lng: 100.043,
    hook: "כמו צ'אוונג רק זול יותר ופחות מתויר.",
    tip: "אם התקציב לחוץ — לישון בלאמאי ולנסוע לצ'אוונג בקטנוע.",
  },
  {
    id: "hin-ta-hin-yai",
    name: "סלעי סבא וסבתא",
    nameEn: "Hin Ta & Hin Yai Rocks",
    region: "samui",
    category: "nature",
    lat: 9.452,
    lng: 100.049,
    hook: "שני סלעים בצורה מאוד לא צנועה. הבדיחה הכי מפורסמת באי.",
    tip: "10 דקות, חינם, בדרך ללאמאי. לא צריך יותר מזה.",
    priceThb: 0,
    duration: "20 דקות",
  },
  {
    id: "na-muang",
    name: "מפלי נא מואנג 1+2",
    nameEn: "Na Muang Waterfalls",
    region: "samui",
    category: "nature",
    lat: 9.453,
    lng: 99.98,
    hook: "מפל 1 נגיש ברגל, מפל 2 גבוה יותר ודורש טיפוס.",
    tip: "לא לקנות טיול פילים בכניסה. הליכה עצמאית למפל 2 היא 30 דקות ומגיעים לאותו מקום.",
    priceThb: 0,
  },
  {
    id: "fishermans-village",
    name: "כפר הדייגים בופוט",
    nameEn: "Fisherman's Village, Bophut",
    region: "samui",
    category: "market",
    lat: 9.56,
    lng: 100.068,
    hook: "רחוב עץ ישן עם ברים ושוק לילה בימי שישי.",
    tip: "שוק שישי נופל בטיול שלכם על ערבי חג/שבת — כדאי להגיע פשוט בערב רגיל, זה יפה גם ככה.",
  },
  {
    id: "secret-buddha-garden",
    name: "הגן הסודי של הבודהה",
    nameEn: "Secret Buddha Garden",
    region: "samui",
    category: "nature",
    lat: 9.488,
    lng: 99.995,
    approx: true,
    hook: "פסלים באמצע ג'ונגל ההרים, עם נוף לכל האי.",
    tip: "הכביש לשם הוא 4x4 בלבד — לא קטנוע ולא רכב רגיל. לקחת ג'יפ מאורגן.",
    priceThb: 80,
  },

  // ─────────────────────────── פוקט ───────────────────────────
  {
    id: "chabad-phuket",
    name: 'בית חב"ד פוקט',
    nameEn: "Chabad House Phuket",
    region: "phuket",
    category: "chabad",
    lat: 7.846,
    lng: 98.296,
    approx: true,
    hook: "בקארון, בין קטה לפאטונג — בית כנסת, מסעדה כשרה וסוכה.",
    details:
      'המרכז הישראלי של כל צד האנדמן. גם המקום להתייעץ לגבי סירות, מוניות וחדרים.',
    tip: "בשמיני עצרת ושמחת תורה (3-4.10) זה יהיה מלא — להירשם שבועות מראש.",
    url: "https://www.chabadthailand.com/",
  },
  {
    id: "kosher-phuket",
    name: 'מסעדה כשרה — חב"ד קארון',
    nameEn: "Kosher Restaurant Karon",
    region: "phuket",
    category: "kosher",
    lat: 7.846,
    lng: 98.296,
    approx: true,
    hook: "המקום להצטייד בו לפני פי פי ולפני ימי שייט.",
    tip: "לבקש מנות ארוזות ליום שאתם בסירה. פי פי היא מדבר כשרות.",
    priceThb: 350,
  },
  {
    id: "patong-bangla",
    name: "פאטונג ובאנגלה רואד",
    nameEn: "Patong & Bangla Road",
    region: "phuket",
    category: "party",
    lat: 7.8925,
    lng: 98.2965,
    hook: "רחוב הלילה הכי מטורף באי. ניאון, בירה, קברטים.",
    tip: "לא הולכים אחרי אף אחד ל'שואו' בקומה שנייה — זו מלכודת חשבון קלאסית. משלמים על כל משקה כשמקבלים אותו.",
    priceThb: 0,
  },
  {
    id: "kata-beach",
    name: "חוף קטה",
    nameEn: "Kata Beach",
    region: "phuket",
    category: "beach",
    lat: 7.818,
    lng: 98.298,
    hook: "החוף המאוזן של פוקט — יפה, גלים לגלישה, פחות מטורף מפאטונג.",
    tip: "בסוף ספטמבר-אוקטובר יש גלים וזרמים באנדמן. דגל אדום = לא נכנסים. באמת.",
  },
  {
    id: "karon-beach",
    name: "חוף קארון",
    nameEn: "Karon Beach",
    region: "phuket",
    category: "beach",
    lat: 7.846,
    lng: 98.294,
    hook: 'החוף הארוך שליד בית חב"ד — הבסיס ההגיוני שלכם בפוקט.',
    tip: 'לישון בקארון: קרוב לחב"ד, 10 דקות מפאטונג בקטנוע, וזול יותר.',
  },
  {
    id: "big-buddha-phuket",
    name: "הבודהה הגדול של פוקט",
    nameEn: "Big Buddha Phuket",
    region: "phuket",
    category: "viewpoint",
    lat: 7.8277,
    lng: 98.312,
    hook: "45 מטר של שיש לבן על ראש ההר, עם נוף ל-360 מעלות.",
    tip: "הכביש למעלה תלול — קטנוע חלש עם שני רוכבים לא יעלה. לעלות בבוקר, בצהריים אין צל.",
    priceThb: 0,
    duration: "שעה",
  },
  {
    id: "promthep",
    name: "כף פרומטפ — שקיעה",
    nameEn: "Promthep Cape",
    region: "phuket",
    category: "viewpoint",
    lat: 7.762,
    lng: 98.305,
    hook: "נקודת השקיעה המפורסמת בפוקט, בקצה הדרומי של האי.",
    tip: "להגיע 40 דקות לפני השקיעה, אחרת אין חנייה ואין מקום. השקיעה שם באוקטובר בערך 18:15.",
    priceThb: 0,
  },
  {
    id: "phuket-old-town",
    name: "העיר העתיקה של פוקט",
    nameEn: "Phuket Old Town",
    region: "phuket",
    category: "market",
    lat: 7.884,
    lng: 98.388,
    hook: "רחובות סינו-פורטוגזיים צבעוניים, גרפיטי ובתי קפה.",
    tip: "שוק הליכה בתלאנג רואד בימי ראשון בערב — 11.10 זה יום הטיסה, אז אולי 4.10 בערב אחרי החג.",
    priceThb: 0,
    duration: "3 שעות",
  },
  {
    id: "phang-nga",
    name: "מפרץ פאנג נגה + אי ג'יימס בונד",
    nameEn: "Phang Nga Bay & James Bond Island",
    region: "phuket",
    category: "boat",
    lat: 8.274,
    lng: 98.501,
    hook: "צוקי גיר שיוצאים מהמים, מערות ים וקיאקים בין המונוליתים.",
    tip: "לבחור סיור לונגטייל קטן ולא ספידבוט ענק של 100 איש. יוצאים מוקדם בבוקר כדי להקדים את הקבוצות.",
    priceThb: 1500,
    duration: "יום שלם",
  },
  {
    id: "wat-chalong",
    name: "ואט צ'אלונג",
    nameEn: "Wat Chalong",
    region: "phuket",
    category: "temple",
    lat: 7.846,
    lng: 98.337,
    hook: "המקדש החשוב בפוקט, עם צ'די בן שלוש קומות.",
    tip: "חינם, בדרך מקארון לעיר העתיקה. חצי שעה מספיקה.",
    priceThb: 0,
  },
  {
    id: "freedom-beach",
    name: "פרידום ביץ'",
    nameEn: "Freedom Beach",
    region: "phuket",
    category: "beach",
    lat: 7.869,
    lng: 98.276,
    hook: "חוף חול לבן מוסתר, מגיעים אליו בלונגטייל מפאטונג.",
    tip: "~1500 באט לסירה הלוך-חזור, מתחלקים בין כולם. לסכם שעת איסוף מראש ולשלם רק בחזרה.",
  },
  {
    id: "similan-closed",
    name: "איי סימילן — סגורים",
    nameEn: "Similan Islands (closed)",
    region: "phuket",
    category: "boat",
    lat: 8.657,
    lng: 97.645,
    hook: "העונה נפתחת רק ב-15 באוקטובר — אחרי הטיסה שלכם הביתה.",
    details:
      "הפארק הלאומי סגור לתיירים במאי-אוקטובר. אם מישהו מוכר לכם שם סיור לסימילן בתאריכים האלה — זו הונאה.",
    tip: "התחליף באזור: פאנג נגה או האיים סביב פי פי.",
  },

  // ─────────────────────────── קו פי פי ───────────────────────────
  {
    id: "tonsai-village",
    name: "כפר טונסאי",
    nameEn: "Tonsai Village",
    region: "phiphi",
    category: "party",
    lat: 7.74,
    lng: 98.775,
    hook: "כל האי במרחק הליכה: סמטאות, ברים, בקטים ומסיבות חוף.",
    tip: "אין מכוניות באי. מזומן — יש כספומטים אבל עם עמלה גבוהה, עדיף למשוך בפוקט.",
  },
  {
    id: "phiphi-viewpoint",
    name: "תצפית פי פי",
    nameEn: "Phi Phi Viewpoint",
    region: "phiphi",
    category: "viewpoint",
    lat: 7.744,
    lng: 98.779,
    hook: "התמונה של תאילנד: שני מפרצים ורצועת חול אחת ביניהם.",
    tip: "30 דקות מדרגות. לעלות בזריחה (5:45) או שעה לפני שקיעה — בצהריים זה תנור.",
    priceThb: 30,
    duration: "שעתיים",
  },
  {
    id: "maya-bay",
    name: "מאיה ביי",
    nameEn: "Maya Bay",
    region: "phiphi",
    category: "boat",
    lat: 7.678,
    lng: 98.766,
    hook: 'המפרץ מ"החוף" עם לאונרדו. נפתח מחדש אחרי שיקום השונית.',
    details:
      "אסור לשחות במפרץ עצמו, ויש מכסת מבקרים. נכנסים דרך רציף בצד האחורי.",
    tip: "לצאת בסיור זריחה (6:00) — מגיעים לפני כל הסירות מפוקט ורואים אותו כמעט ריק.",
    priceThb: 400,
  },
  {
    id: "bamboo-island",
    name: "אי הבמבוק",
    nameEn: "Bamboo Island",
    region: "phiphi",
    category: "beach",
    lat: 7.833,
    lng: 98.814,
    hook: "חול לבן ומים תכולים בלי כלום מסביב. הכי קרוב לגלויה.",
    tip: "חלק מרוב סיורי היום. השנרקול סביבו טוב יותר מבמאיה ביי.",
    priceThb: 400,
  },
  {
    id: "long-beach-phiphi",
    name: "לונג ביץ'",
    nameEn: "Long Beach (Hat Yao)",
    region: "phiphi",
    category: "beach",
    lat: 7.729,
    lng: 98.776,
    hook: "שקט יחסית לטונסאי, עם שונית לשנרקול ישר מהחוף.",
    tip: "טקסי-בוט מטונסאי ~150 באט, או 30 דקות הליכה בשפל.",
  },
  {
    id: "phiphi-no-kosher",
    name: "אין כשרות בפי פי",
    nameEn: "No kosher on Phi Phi",
    region: "phiphi",
    category: "kosher",
    lat: 7.7405,
    lng: 98.7765,
    hook: 'האי היחיד במסלול בלי בית חב"ד ובלי מסעדה כשרה.',
    details:
      'בית חב"ד הקרוב הוא בקראבי/אאו נאנג ביבשת, או בפוקט. לתכנן את פי פי כאמצע שבוע בלבד.',
    tip: "להביא מפוקט: טונה, קרקרים, חמאת בוטנים, נודלס כשרים ופירות. בסופר של טונסאי יש פירות ומים.",
  },
  {
    id: "chabad-krabi",
    name: 'בית חב"ד קראבי / אאו נאנג',
    nameEn: "Chabad Krabi (Ao Nang)",
    region: "phiphi",
    category: "chabad",
    lat: 8.032,
    lng: 98.825,
    approx: true,
    hook: 'החב"ד הקרוב לפי פי — ביבשת, שעה וחצי במעבורת.',
    tip: "רלוונטי רק אם אתם משנים מסלול ועוברים דרך קראבי. לוודא שהוא פעיל בעונה.",
    url: "https://www.chabadthailand.com/",
  },

  // ─────────────────── תחבורה בין האזורים ───────────────────
  {
    id: "ferry-samui-phangan",
    name: "מעבורת סמוי ↔ קופנגן",
    nameEn: "Samui ↔ Phangan Ferry",
    region: "samui",
    category: "transport",
    lat: 9.5678,
    lng: 100.062,
    hook: "30-45 דקות בין האיים. לומפראיה / סונגסרם, כמה יציאות ביום.",
    tip: "מרציף הבודהה הגדול או נאת'ון. ~300-400 באט. להזמין יום מראש בעונה, ולא לתכנן מעבורת אחרונה בערב חג.",
    priceThb: 350,
  },
  {
    id: "samui-airport",
    name: "נמל התעופה קוסמוי (USM)",
    nameEn: "Koh Samui Airport",
    region: "samui",
    category: "transport",
    lat: 9.5479,
    lng: 100.0622,
    hook: "שדה גן פתוח וחמוד — וגם היקר בתאילנד (בנגקוק אייר).",
    tip: "חלופה זולה: טיסה לסוראט ת'אני + אוטובוס+מעבורת. מוסיף 4-5 שעות וחוסך הרבה.",
  },
  {
    id: "phuket-airport",
    name: "נמל התעופה פוקט (HKT)",
    nameEn: "Phuket Airport",
    region: "phuket",
    category: "transport",
    lat: 8.1132,
    lng: 98.3169,
    hook: "השדה הגדול של הדרום, שעה מקארון.",
    tip: "מיניבוס משותף ~200 באט, גראב ~700-900. להזמין גראב מחוץ לטרמינל — בפנים המוניות מאורגנות ויקרות.",
  },
  {
    id: "rassada-pier",
    name: "רציף ראסאדה — מעבורת לפי פי",
    nameEn: "Rassada Pier",
    region: "phuket",
    category: "transport",
    lat: 7.8797,
    lng: 98.4083,
    hook: "מכאן יוצאות המעבורות לקו פי פי, ~2 שעות.",
    tip: "יציאות בערך 8:30 / 11:00 / 14:30. ~450 באט. בים סוער באוקטובר לפעמים מבטלים — לשמור יום גמישות.",
    priceThb: 450,
  },
  {
    id: "bkk-airport",
    name: "סוברנבומי (BKK)",
    nameEn: "Suvarnabhumi Airport",
    region: "bangkok",
    category: "transport",
    lat: 13.69,
    lng: 100.7501,
    hook: "שדה הנחיתה מישראל, 30 ק\"מ ממרכז בנגקוק.",
    tip: "רכבת ה-ARL עד פאיה תאי ואז מונית/BTS, או גראב ישר לקאו סאן (~400 באט). לא לוקחים מונית שמסרבת למונה.",
  },
  {
    id: "don-mueang",
    name: "דון מואנג (DMK)",
    nameEn: "Don Mueang Airport",
    region: "bangkok",
    category: "transport",
    lat: 13.9126,
    lng: 100.6068,
    hook: "שדה הלואו-קוסט — מכאן טסים לרוב לסמוי דרך סוראט ת'אני, ולפוקט.",
    tip: "המעבר בין BKK ל-DMK הוא שעה-שעתיים בפקק. אף פעם לא לתכנן קונקשן קצר ביניהם.",
  },
];

export const PLACE_BY_ID = Object.fromEntries(
  PLACES.map((p) => [p.id, p]),
) as Record<string, Place>;
